### ISSUE TITLE
Добавте пожалуйста датчик движения tuya.

### ISSUE THREAD

**Issue by RodionFoto** [u236/homed-service-zigbee#100]
<html>
<body>

Logical type | end device
-- | --
Power source |  
IEEE address | a4:c1:38:f9:d9:d5:9a:5a
Network address | 0xce08
Manufacturer code | 0x1141
Manufacturer name | _TZE200_3towulqd
Model name | TS0601
Interview finished |  
Supported |  
Active |  

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by Crazy-Child** [comment]
Попробуйте заменить файл tuya.json на этот:
https://github.com/Crazy-Child/homed-service-zigbee/blob/master/deploy/data/usr/share/homed-zigbee/tuya.json
в /usr/share/homed-zigbee у вас на устройстве
