### ISSUE TITLE
Aqara Opple 6-Key Wireless Switch WXCJKG13LM    Не работает!!!  Нет реакции на нажатия кнопок.

### ISSUE THREAD

**Issue by RodionFoto** [u236/homed-service-zigbee#101]
![2023-12-20_10-05-42](https://github.com/u236/homed-service-zigbee/assets/120686044/b2df72ff-febd-4d47-b202-92dde351f725)
![2023-12-20_10-05-05](https://github.com/u236/homed-service-zigbee/assets/120686044/280fd665-300b-439f-976f-e1dc815564cf)

**Comment by u236** [comment]
Скорее всего работает, нужно просто поменять режим (command/event), один тз этих режимов нужен для прямого биндинга на светильники, второй будет слать нажатия кнопок. Какой из них какой - не помню. При сметне режима нужно будить выключатель коротким нажатием на кнорку сопряжения.
