### ISSUE TITLE
прошу добавить датчик присутствия "_TZE204_kyhbrfyl", model name is "TS0601"

### ISSUE THREAD

**Issue by Sborkahome** [u236/homed-service-zigbee#107]
Sun Jan  7 14:02:10 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:10.354 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" interview started...
Sun Jan  7 14:02:10 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:10.640 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" node descriptor received, manufacturer code is "0x1141" and logical type is "router"
Sun Jan  7 14:02:10 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:10.725 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" active endpoints received: "0x01, 0xf2"
Sun Jan  7 14:02:10 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:10.813 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" simple descriptor received
Sun Jan  7 14:02:10 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:10.899 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0xf2" simple descriptor received
Sun Jan  7 14:02:10 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:10.994 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0x0001" report received with type "0x20" and data "4a" and transaction id 30
Sun Jan  7 14:02:11 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:10.999 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0x0004" report received with type "0x42" and data "5f:54:5a:45:32:30:34:5f:6b:79:68:62:72:66:79:6c" and transaction id 30
Sun Jan  7 14:02:11 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:11.003 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0x0005" report received with type "0x42" and data "54:53:30:36:30:31" and transaction id 30
Sun Jan  7 14:02:11 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:11.008 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0x0007" report received with type "0x30" and data "01" and transaction id 30
Sun Jan  7 14:02:11 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:11.012 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0x4000" report received with type "0x00" and data "(empty)" and transaction id 30
Sun Jan  7 14:02:11 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:11.016 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" manufacturer name is "_TZE204_kyhbrfyl" and model name is "TS0601"
Sun Jan  7 14:02:11 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:11.133 (wrn) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" manufacturer name "_TZE204_kyhbrfyl" and model name "TS0601" not found in library
Sun Jan  7 14:02:11 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:11.138 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" identified as "_TZE204_kyhbrfyl/TS0601"
Sun Jan  7 14:02:11 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:11.142 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" interview finished successfully
Sun Jan  7 14:02:16 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:16.644 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x11" received with payload "04:05:4a" and transaction id 125
Sun Jan  7 14:02:16 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:16.648 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x11" with payload "04:05:4a"
Sun Jan  7 14:02:16 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:16.744 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" received with payload "04:04:01:04:00:01:01" and transaction id 126
Sun Jan  7 14:02:16 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:16.748 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" with payload "04:04:01:04:00:01:01"
Sun Jan  7 14:02:16 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:16.843 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" received with payload "04:05:0b:04:00:01:02" and transaction id 127
Sun Jan  7 14:02:16 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:16.848 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" with payload "04:05:0b:04:00:01:02"
Sun Jan  7 14:02:16 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:16.944 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" received with payload "04:06:13:02:00:04:00:00:00:4e" and transaction id 128
Sun Jan  7 14:02:16 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:16.948 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" with payload "04:06:13:02:00:04:00:00:00:4e"
Sun Jan  7 14:02:17 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:17.040 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" received with payload "04:07:13:02:00:04:00:00:00:72" and transaction id 129
Sun Jan  7 14:02:17 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:17.044 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" with payload "04:07:13:02:00:04:00:00:00:72"
Sun Jan  7 14:02:17 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:17.339 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" received with payload "04:08:13:02:00:04:00:00:00:8a" and transaction id 130
Sun Jan  7 14:02:17 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:17.343 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" with payload "04:08:13:02:00:04:00:00:00:8a"
Sun Jan  7 14:02:17 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:17.740 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" received with payload "04:09:13:02:00:04:00:00:00:9e" and transaction id 131
Sun Jan  7 14:02:17 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:17.744 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" with payload "04:09:13:02:00:04:00:00:00:9e"
Sun Jan  7 14:02:17 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:17.840 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" requested local time
Sun Jan  7 14:02:23 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:23.221 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" received with payload "04:0a:01:04:00:01:00" and transaction id 133
Sun Jan  7 14:02:23 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:23.226 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" with payload "04:0a:01:04:00:01:00"
Sun Jan  7 14:02:23 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:23.319 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" received with payload "04:0b:0b:04:00:01:00" and transaction id 134
Sun Jan  7 14:02:23 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:23.323 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0xef00" command "0x02" with payload "04:0b:0b:04:00:01:00"
Sun Jan  7 14:02:24 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:24.808 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0x0001" report received with type "0x20" and data "4a" and transaction id 135
Sun Jan  7 14:02:24 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:24.813 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0xffe2" report received with type "0x20" and data "38" and transaction id 135
Sun Jan  7 14:02:24 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:24.817 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0xffe2" report with type "0x20" and data "38"
Sun Jan  7 14:02:24 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:24.821 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0xffe4" report received with type "0x20" and data "00" and transaction id 135
Sun Jan  7 14:02:24 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:24.826 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0xffe4" report with type "0x20" and data "00"
Sun Jan  7 14:02:25 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:25.124 (inf) zigbee:    Device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0xffdf" report received with type "0x42" and data "46:6b:2d:2d:13:5e:6b:2d:2d:65:5f:6b:2d:2d:12" and transaction id 136
Sun Jan  7 14:02:25 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:25.129 (wrn) zigbee:    No property found for device "a4:c1:38:be:c5:d5:53:9b" endpoint "0x01" cluster "0x0000" attribute "0xffdf" report with type "0x42" and data "46:6b:2d:2d:13:5e:6b:2d:2d:65:5f:6b:2d:2d:12"
Sun Jan  7 14:02:43 2024 daemon.info homed-zigbee[1873]: 2024.01.07 14:02:43.089 (inf) zigbee:    Permit join disabled successfully

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/95b744cc111d6a4bf7fd02b9acc7828655858017

**Comment by Sborkahome** [comment]
немного изменил:
    {
      "description":    "TUYA TS0601 Human Presence Sensor (Type E)",
      "modelNames":     ["_TZE204_kyhbrfyl"],
      "properties":     ["tuyaDataPoints"],
      "actions":        ["tuyaDataPoints"],
      "exposes":        ["occupancy", "motionStatus", "targetDistance", "sensitivity", "motionSensitivity", "distanceMax", "fadingTime"],
      "options":        {
                          "tuyaDataPoints":
                          {
                            "1":    [{"name": "occupancy", "type": "bool"}],
                            "11":   [{"name": "motionStatus", "type": "enum"}],
                            "12":   [{"name": "fadingTime", "type": "value", "action": true}],
                            "13":   [{"name": "distanceMax", "type": "value", "divider": 100, "action": true}],
                            "15":   [{"name": "sensitivity", "type": "value", "action": true}],
                            "16":   [{"name": "motionSensitivity", "type": "value", "action": true}],
                            "19":   [{"name": "targetDistance", "type": "value", "divider": 100}]
                          },

                          "motionStatus": {"enum": ["none", "small", "large"]},
                          "fadingTime": {"min": 0, "max": 300, "step": 10},
                          "distanceMax": {"min": 1.5, "max": 6, "step": 0.1},
                          "sensitivity": {"min": 0, "max": 7},
                          "motionSensitivity": {"min": 1, "max": 7}
                        }
    },

**Comment by u236** [comment]
да, спасибо, обновил - https://github.com/u236/homed-service-zigbee/commit/a575bf8de726f96596f49c5d74d54de39bc08470
