### ISSUE TITLE
Relay Tuya TS0001 (_TZ3000_npzfdcof)

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#11]
2022.10.26 16:32:33.062 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" joined network with address "0xB7CF"
2022.10.26 16:32:33.067 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" rejoined network with address "0xB7CF"
2022.10.26 16:32:33.165 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" is router
2022.10.26 16:32:33.168 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" node descriptor received, manufacturer code: "0x1141"
2022.10.26 16:32:33.171 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" is router
2022.10.26 16:32:33.174 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" node descriptor received, manufacturer code: "0x1141"
2022.10.26 16:32:33.236 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" is router
2022.10.26 16:32:33.239 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" node descriptor received, manufacturer code: "0x1141"
2022.10.26 16:32:33.243 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" is router
2022.10.26 16:32:33.247 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" node descriptor received, manufacturer code: "0x1141"
2022.10.26 16:32:33.320 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" active endpoints received: "0x01, 0xF2"
2022.10.26 16:32:33.324 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" active endpoints received: "0x01, 0xF2"
2022.10.26 16:32:33.404 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" simple descriptor received
2022.10.26 16:32:33.407 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" simple descriptor received
2022.10.26 16:32:33.479 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" endpoint "0xF2" simple descriptor received
2022.10.26 16:32:33.483 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" endpoint "0xF2" simple descriptor received
2022.10.26 16:32:33.608 (wrn) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" manufacturer name "_TZ3000_npzfdcof" unrecognized
2022.10.26 16:32:33.612 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" manufacturer name is "_TZ3000_npzfdcof" and model name is "TS0001"
2022.10.26 16:32:33.617 (inf) zigbee:    Device "a4:c1:38:fd:92:ed:96:33" interview finished
2022.10.26 16:32:39.730 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0xE000" attribute "0xD003" with data type "0x42" and data "41:41:41:41"
2022.10.26 16:32:39.733 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0xE000" attribute "0xD003" with data type "0x42" and data "41:41:41:41"
2022.10.26 16:32:39.814 (wrn) zigbee:    Unrecognized attribute "0xD001" data type "0x48" received from device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0xE000" with payload: "02:00:06"
2022.10.26 16:32:39.817 (wrn) zigbee:    Unrecognized attribute "0xD001" data type "0x48" received from device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0xE000" with payload: "02:00:06"
2022.10.26 16:32:39.900 (wrn) zigbee:    Unrecognized attribute "0xD002" data type "0x48" received from device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0xE000" with payload: "02:00:0a"
2022.10.26 16:32:39.903 (wrn) zigbee:    Unrecognized attribute "0xD002" data type "0x48" received from device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0xE000" with payload: "02:00:0a"
2022.10.26 16:32:39.985 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x0000" with data type "0x10" and data "00"
2022.10.26 16:32:39.988 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x4001" with data type "0x21" and data "00:00"
2022.10.26 16:32:39.991 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x4002" with data type "0x21" and data "00:00"
2022.10.26 16:32:39.995 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x8002" with data type "0x30" and data "02"
2022.10.26 16:32:39.998 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x0000" with data type "0x10" and data "00"
2022.10.26 16:32:40.002 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x4001" with data type "0x21" and data "00:00"
2022.10.26 16:32:40.005 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x4002" with data type "0x21" and data "00:00"
2022.10.26 16:32:40.008 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x8002" with data type "0x30" and data "02"
2022.10.26 16:32:40.087 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0xE001" attribute "0xD030" with data type "0x30" and data "00"
2022.10.26 16:32:40.091 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0xE001" attribute "0xD030" with data type "0x30" and data "00"
2022.10.26 16:32:43.616 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x0000" with data type "0x10" and data "01"
2022.10.26 16:32:43.620 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x0000" with data type "0x10" and data "01"
2022.10.26 16:32:44.845 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x0000" with data type "0x10" and data "00"
2022.10.26 16:32:44.848 (wrn) zigbee:    No property found for device "a4:c1:38:fd:92:ed:96:33" endpoint "0x01" cluster "0x0006" attribute "0x0000" with data type "0x10" and data "00"

**Comment by d51x** [comment]
![photo_2022-10-26_16-37-45](https://user-images.githubusercontent.com/10882718/198041298-b0f928f9-9ff5-4deb-b93c-a84f817eba14.jpg)

**Comment by u236** [comment]
Added (partialy) in https://github.com/u236/homed-service-zigbee/commit/28aeb9e8c241788670b4de33044538ac4e303d05.

**Comment by u236** [comment]
Added in https://github.com/u236/homed-service-zigbee/commit/d3dc48a544cf043612d82aca37a4a979bc428263.
