### ISSUE TITLE
Добавить поддержку устройств

### ISSUE THREAD

**Issue by spuch-apuch** [u236/homed-service-zigbee#111]
Датчик утечки газа Xiaomi Mijia Honeywell Gas Detector (JTQJ-BF-01LM/BW)

<img width="1022" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/10628027/95a4f154-520e-4efd-b855-121dbcaebcde">

Tuya выключатель света (_TZ3000_oex7egmt)

<img width="1006" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/10628027/72f181bc-cc5c-4571-908e-1867b1743037">

Заранее спасибо!

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/b8bf4598cde7f932ad521d6d55d56b43d08c0c11
