### ISSUE TITLE
Поддержка беспроводного выключателя Aqara

### ISSUE THREAD

**Issue by KeNt606** [u236/homed-service-zigbee#115]
Description:	LUMI/lumi.sensor_86sw2
Manufacturer name:	LUMI
Model name:	lumi.sensor_86sw2
IEEE address:	00:15:8d:00:02:37:e9:fd
![Screenshot_2024-01-15-20-50-28-019_com android chrome~2](https://github.com/u236/homed-service-zigbee/assets/50424575/aea668fd-1d2d-4125-b01d-741479133b13)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/5e7e0564a933eee1b38a906b38e6a796d999b2e8
