### ISSUE TITLE
Поддержка выключателя Aqara

### ISSUE THREAD

**Issue by KeNt606** [u236/homed-service-zigbee#116]
Description: LUMI/lumi.ctrl_ln2.aq1
Manufacturer name: LUMI
Model name: lumi.ctrl_ln2.aq1
IEEE address: 00:15:8d:00:04:21:b6:cc
![Screenshot_2024-01-15-20-53-01-035_com android chrome~2](https://github.com/u236/homed-service-zigbee/assets/50424575/9a110163-8283-4520-9abe-1da17125ed6d)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/5e7e0564a933eee1b38a906b38e6a796d999b2e8
