### ISSUE TITLE
Поддержка Tuya TS0202_2 и TS004F

### ISSUE THREAD

**Issue by Velomeloman** [u236/homed-service-zigbee#117]
Прошу добавить 
https://www.zigbee2mqtt.io/devices/TS0202_2.html
_TZ3210_cwamkvua

https://www.zigbee2mqtt.io/devices/TS004F.html
_TZ3000_xabckq1v

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/5e7e0564a933eee1b38a906b38e6a796d999b2e8
