### ISSUE TITLE
Permit join при старте сервиса

### ISSUE THREAD

**Issue by Blacksli** [u236/homed-service-zigbee#119]
При старте сервиса не хорошо если восстанавливается последнее состояние.  Не важно что делал до рестарта - не ожидается  что координатор ждет новых устройства в свою сеть. Может что-то глюкануло или еще что. Т.е. надо всегда держать на контроле пермит.
Если кому это нужно - лучше вынести в параметр, который по умолчанию off 
Варианты - on  off last

**Comment by Blacksli** [comment]
автор не рассматривает новые функции.

**Comment by u236** [comment]
уточнение - автор рассматривает новые функции, но оставляет за собой права решать, нужны ли они

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/c787333925e4db503506b2a862f739beffcca7f4
