### ISSUE TITLE
Поддержка GS Gas Sensor SGMHM-I1

### ISSUE THREAD

**Issue by tigor-ussr** [u236/homed-service-zigbee#122]
Приветствую!
Добавь пожалуйста
![image](https://github.com/u236/homed-service-zigbee/assets/78240677/678119c0-6c15-41e9-8078-7e3b3c239f6e)
[gs.json](https://github.com/u236/homed-service-zigbee/files/14158904/gs.json)
Спасибо.

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/73c8e30075ed157b694560c21c38ca1b85ff9245
