### ISSUE TITLE
please add Philips Hue motion sensor

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-zigbee#123]
Philips  model 9290019758 
https://www.zigbee2mqtt.io/devices/9290019758.html

<img width="573" alt="изображение" src="https://github.com/u236/homed-service-zigbee/assets/77930301/5b502981-a02c-4734-bd92-948fca5ddf2e">

2024.02.08 13:24:31.284 (inf) zigbee:    Permit join enabled successfully
2024.02.08 13:24:51.094 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" joined network with address "0xbcc6"
2024.02.08 13:24:51.098 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" interview started...
2024.02.08 13:24:52.944 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" node descriptor received, manufacturer code is "0x100b" and logical type is "end device"
2024.02.08 13:24:53.452 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" active endpoints received: "0x02, 0x01"
2024.02.08 13:24:53.965 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x01" simple descriptor received
2024.02.08 13:24:54.459 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x02" simple descriptor received
2024.02.08 13:24:55.041 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" manufacturer name is "Philips" and model name is "SML002"
2024.02.08 13:24:55.141 (wrn) zigbee:    Device "00:17:88:01:06:47:de:d9" manufacturer name "Philips" and model name "SML002" not found in library
2024.02.08 13:24:55.144 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x02" properties recognized: "battery, occupancy, illuminance, temperature"
2024.02.08 13:24:55.148 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x02" exposes: "battery, occupancy, illuminance, temperature"
2024.02.08 13:24:55.151 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" firmware is "6.1.1.27575"
2024.02.08 13:24:55.155 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" identified as "Philips/SML002"
2024.02.08 13:24:55.476 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x02" cluster "0x0001" binding finished successfully
2024.02.08 13:24:55.977 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x02" cluster "0x0400" binding finished successfully
2024.02.08 13:24:56.476 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x02" cluster "0x0402" binding finished successfully
2024.02.08 13:24:56.966 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x02" battery reporting configuration request finished successfully
2024.02.08 13:24:57.468 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x02" illuminance reporting configuration request finished successfully
2024.02.08 13:24:57.968 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" endpoint "0x02" temperature reporting configuration request finished successfully
2024.02.08 13:24:57.973 (inf) zigbee:    Device "00:17:88:01:06:47:de:d9" interview finished successfully
2024.02.08 13:25:07.572 (inf) zigbee:    Permit join disabled successfully

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/991bd7816fe7794a4fd8f51b16bad0b610bde41d
