### ISSUE TITLE
Перестала поддерживаться лампа, после апдейта.

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-zigbee#124]
![telegram-cloud-photo-size-4-5927281149288234125-y](https://github.com/u236/homed-service-zigbee/assets/77930301/95ea4745-ddd2-4ceb-a935-b7ef29b157b3)

Permit join enabled successfully
2024.02.11 08:41:29.538 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" joined network with address "0xdab6"
2024.02.11 08:41:29.541 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" interview started...
2024.02.11 08:41:29.647 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" node descriptor received, manufacturer code is "0x0000" and logical type is "router"
2024.02.11 08:41:29.829 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" active endpoints received: "0x01, 0x0d"
2024.02.11 08:41:29.906 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" simple descriptor received
2024.02.11 08:41:29.985 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x0d" simple descriptor received
2024.02.11 08:41:30.176 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" color capabilities: "0x001f"
2024.02.11 08:41:30.190 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" manufacturer name is "eWeLight" and model name is "ZB-CL01"
2024.02.11 08:41:30.363 (wrn) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" manufacturer name "eWeLight" and model name "ZB-CL01" not found in library
2024.02.11 08:41:30.366 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" properties recognized: "status, level, color, colorTemperature"
2024.02.11 08:41:30.370 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" actions recognized: "status, level, color, colorTemperature"
2024.02.11 08:41:30.373 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" exposes: "light"
2024.02.11 08:41:30.376 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" firmware is "1.0.13"
2024.02.11 08:41:30.380 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" identified as "eWeLight/ZB-CL01"
2024.02.11 08:41:32.056 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" cluster "0x0006" binding finished successfully
2024.02.11 08:41:32.133 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" cluster "0x0008" binding finished successfully
2024.02.11 08:41:32.204 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" cluster "0x0300" binding finished successfully
2024.02.11 08:41:32.284 (wrn) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" cluster "0x0006" command "0x06" default response received with error, status code: "0x82"
2024.02.11 08:41:32.289 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" status reporting configuration request finished successfully
2024.02.11 08:41:32.366 (wrn) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" cluster "0x0008" command "0x06" default response received with error, status code: "0x82"
2024.02.11 08:41:32.370 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" level reporting configuration request finished successfully
2024.02.11 08:41:32.446 (wrn) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" cluster "0x0300" command "0x06" default response received with error, status code: "0x82"
2024.02.11 08:41:32.450 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" colorHS reporting configuration request finished successfully
2024.02.11 08:41:32.528 (wrn) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" cluster "0x0300" command "0x06" default response received with error, status code: "0x82"
2024.02.11 08:41:32.532 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" endpoint "0x01" colorTemperature reporting configuration request finished successfully
2024.02.11 08:41:32.535 (inf) zigbee:    Device "00:12:4b:00:23:9d:e9:3c" interview finished successfully

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/a0b6a6a2984486ad2035b019f88e8b64b5c8acf0
