### ISSUE TITLE
Не работает  "occupancy" (и не работало) Philips Hue Motion Sensor 9290019758

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-zigbee#127]
Дважды удалял и спаривал датчик движения , так и не заработало.
Перестало работать состояние  "battery"

<img width="613" alt="изображение" src="https://github.com/u236/homed-service-zigbee/assets/77930301/4cff616e-5f91-48b5-9a62-c83e2cf27c5a">

при перегузке страницы

<img width="550" alt="изображение" src="https://github.com/u236/homed-service-zigbee/assets/77930301/1762c648-defa-4eda-8b45-a8f4502f0a36">

Permit join enabled successfully
2024.02.22 11:38:51.470 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" rejoined network with address "0x4251"
2024.02.22 11:38:51.474 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" network address updated
2024.02.22 11:38:51.477 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" interview started...
2024.02.22 11:38:53.308 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" node descriptor received, manufacturer code is "0x100b" and logical type is "end device"
2024.02.22 11:38:53.819 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" active endpoints received: "0x02, 0x01"
2024.02.22 11:38:54.332 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x01" simple descriptor received
2024.02.22 11:38:54.852 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" simple descriptor received
2024.02.22 11:38:55.390 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" manufacturer name is "Philips" and model name is "SML002"
2024.02.22 11:38:55.412 (wrn) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" property "battery" unrecognized
2024.02.22 11:38:55.417 (wrn) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" property "hueSensitivityMode" unrecognized
2024.02.22 11:38:55.421 (wrn) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" binding "occupancy" unrecognized
2024.02.22 11:38:55.424 (wrn) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" reporting "occupancy" unrecognized
2024.02.22 11:38:55.429 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" firmware is "6.1.1.27575"
2024.02.22 11:38:55.432 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" identified as "Philips Hue Motion Sensor 9290019758"
2024.02.22 11:38:55.898 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" cluster "0x0001" binding finished successfully
2024.02.22 11:38:56.404 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" cluster "0x0400" binding finished successfully
2024.02.22 11:38:56.899 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" cluster "0x0402" binding finished successfully
2024.02.22 11:38:57.390 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" battery reporting configuration request finished successfully
2024.02.22 11:38:57.890 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" illuminance reporting configuration request finished successfully
2024.02.22 11:38:58.390 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" endpoint "0x02" temperature reporting configuration request finished successfully
2024.02.22 11:38:58.393 (inf) zigbee:    Device "Ð”Ð²Ð¾Ñ€" interview finished successfully

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/825e97cae6795f3dba5c2fa6c9e134be0d3cfa14
