### ISSUE TITLE
чекбокс - не добавилась "поддержка" лампы eWeLight/ZB-CL01

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-zigbee#128]
<img width="512" alt="изображение" src="https://github.com/u236/homed-service-zigbee/assets/77930301/f53e6571-1db9-4fba-9900-a46ccbb45ead">

**Comment by u236** [comment]
перепутал eWeLink и eWeLight
https://github.com/u236/homed-service-zigbee/commit/b1be6844790685153e13931627b9af0049c6439a
