### ISSUE TITLE
Новые настройки для датчиков температуры LYWSD03MMC

### ISSUE THREAD

**Issue by Deniom3** [u236/homed-service-zigbee#129]
В прошивке 1.1.0 для датчиков добавили два новых атрибута настройки отключение экрана и отключения смайлика.

https://github.com/devbis/z03mmc/releases/tag/1.1.0

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/8c8a4da9c381adc9ccddd6a1d6eed3501f652a6f
