### ISSUE TITLE
Smoke Detector Tuya TS0205 (_TYZB01_dsjszp0x)

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#13]
https://aliexpress.ru/item/4001220370806.html

2022.10.26 16:49:39.618 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" joined network with address "0x3451"
2022.10.26 16:49:39.621 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" rejoined network with address "0x3451"
2022.10.26 16:49:40.636 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" node descriptor received, manufacturer code: "0x0000"
2022.10.26 16:49:40.639 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" node descriptor received, manufacturer code: "0x0000"
2022.10.26 16:49:41.648 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" active endpoints received: "0x01"
2022.10.26 16:49:41.651 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" active endpoints received: "0x01"
2022.10.26 16:49:42.173 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" endpoint "0x01" simple descriptor received
2022.10.26 16:49:42.176 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" endpoint "0x01" simple descriptor received
2022.10.26 16:49:54.301 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" endpoint "0x01" IAS zone enrolled
2022.10.26 16:49:54.309 (wrn) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" manufacturer name "_TYZB01_dsjszp0x" unrecognized
2022.10.26 16:49:54.312 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" manufacturer name is "_TYZB01_dsjszp0x" and model name is "TS0205"
2022.10.26 16:49:54.316 (inf) zigbee:    Device "84:fd:27:ff:fe:69:4f:41" interview finished
2022.10.26 16:50:01.096 (wrn) zigbee:    No property found for device "84:fd:27:ff:fe:69:4f:41" endpoint "0x01" cluster "0x0500" command "0x00" with payload "01:00:00:42:00:00:02"
2022.10.26 16:50:01.099 (wrn) zigbee:    No property found for device "84:fd:27:ff:fe:69:4f:41" endpoint "0x01" cluster "0x0500" command "0x00" with payload "01:00:00:42:00:00:02"
2022.10.26 16:50:03.116 (wrn) zigbee:    No property found for device "84:fd:27:ff:fe:69:4f:41" endpoint "0x01" cluster "0x0500" command "0x00" with payload "00:00:00:42:00:00:02"
2022.10.26 16:50:03.119 (wrn) zigbee:    No property found for device "84:fd:27:ff:fe:69:4f:41" endpoint "0x01" cluster "0x0500" command "0x00" with payload "00:00:00:42:00:00:02"
2022.10.26 16:50:09.878 (wrn) zigbee:    No property found for device "84:fd:27:ff:fe:69:4f:41" endpoint "0x01" cluster "0x0001" attribute "0x0021" with data type "0x20" and data "c8"
2022.10.26 16:50:09.881 (wrn) zigbee:    No property found for device "84:fd:27:ff:fe:69:4f:41" endpoint "0x01" cluster "0x0001" attribute "0x0021" with data type "0x20" and data "c8"

**Comment by u236** [comment]
Added in https://github.com/u236/homed-service-zigbee/commit/75f7e5e16f9f0eac333bb6f4ea45aa67a05ff075.
