### ISSUE TITLE
Поддержка TS0011 ( _TZ3000_hafsquare )

### ISSUE THREAD

**Issue by seregahere** [u236/homed-service-zigbee#130]
Здравствуйте, прошу добавить поддержку безнулевого реле: 
_TZ3000_hafsqare/TS0011

![image](https://github.com/u236/homed-service-zigbee/assets/5401746/e174e55b-6a8a-4059-8c86-5d930a80584c)

Если это поможет, похожее Вы уже недавно добавляли https://github.com/u236/homed-service-zigbee/issues/121

В zigbee2mqtt определяется как https://www.zigbee2mqtt.io/devices/TS0011.html (на скрине такой же выключатель, из одной партии)
![image](https://github.com/u236/homed-service-zigbee/assets/5401746/0753f0b5-a448-45b7-bd67-7212e9e62f93)

Спасибо!

**Comment by seregahere** [comment]
Только что попробовал проапдейтить /usr/share/homed-zigbee/tuya.json
После рестарта homed-zigbee реле стало поддерживаемым:
![image](https://github.com/u236/homed-service-zigbee/assets/5401746/43a970e6-db34-4729-aeae-2b0b12bd6b9d)

Если Вы не против, могу сделать PR.

**Comment by u236** [comment]
> Если Вы не против, могу сделать PR.

Да, конечно, буду только рад :)
