### ISSUE TITLE
Добавте по возможности SONOFF/SNZB-06P, спасибо

### ISSUE THREAD

**Issue by cgtut** [u236/homed-service-zigbee#133]
![chrome_ZEBaiQMUUv](https://github.com/u236/homed-service-zigbee/assets/82533683/780571b1-0533-4940-b17e-873599321488)
![chrome_i1qjscJemD](https://github.com/u236/homed-service-zigbee/assets/82533683/876e2c6e-6dd4-4316-89bd-3bfd6d23e4fe)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/3ee40f90c37f218bf22d4c59ffb0a0496b37bfa7
