### ISSUE TITLE
Добавить поддержку лампы CK-BL702-AL-01

### ISSUE THREAD

**Issue by RavenHuginn** [u236/homed-service-zigbee#136]
Прошу рассмотреть возможность добавить поддержку лампы.

![image](https://github.com/u236/homed-service-zigbee/assets/20950826/51ac6fcc-abf8-475b-bc3b-5789ccc2e010)

https://www.zigbee2mqtt.io/devices/CK-BL702-AL-01.html

![image](https://github.com/u236/homed-service-zigbee/assets/20950826/79bb0264-e0b6-49d6-b92f-9495f68ceeda)

**Comment by u236** [comment]
почему закрыли ишью? лампа же еще не поддерживается :)

**Comment by RavenHuginn** [comment]
Нашёл решение, добавление информации по устройству в файл sonoff.json.

`,
    {
      "description":    "eWeLink/CK-BL702-AL-01(7009_Z102LG03-1)",
      "modelNames":     ["CK-BL702-AL-01(7009_Z102LG03-1)"],
      "properties":     ["status", "level", "colorXY", "colorTemperature"],
      "actions":        ["status", "level", "colorXY", "colorTemperature"],
      "exposes":        ["light"],
      "options":        {"light": ["level", "color", "colorTemperature"], "colorTemperature": {"min": 142, "max": 500}, "powerSource": 1}
    }`

Не совсем знаю как это всё правильно оформлять

**Comment by u236** [comment]
я сделаю, пускай пока ишью повисит открытым :)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/1ed99075f0e1a215e6c4a5b619df63ea2856d1ce
