### ISSUE TITLE
Power Link Perenio PEHPL0X

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#14]
2022.10.26 16:52:47.069 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" joined network with address "0x2F64"
2022.10.26 16:52:47.073 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" rejoined network with address "0x2F64"
2022.10.26 16:52:47.164 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" is router
2022.10.26 16:52:47.167 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" node descriptor received, manufacturer code: "0x1234"
2022.10.26 16:52:47.171 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" is router
2022.10.26 16:52:47.174 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" node descriptor received, manufacturer code: "0x1234"
2022.10.26 16:52:47.241 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" is router
2022.10.26 16:52:47.243 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" node descriptor received, manufacturer code: "0x1234"
2022.10.26 16:52:47.247 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" is router
2022.10.26 16:52:47.250 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" node descriptor received, manufacturer code: "0x1234"
2022.10.26 16:52:47.337 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" active endpoints received: "0x01, 0x0A, 0xF2"
2022.10.26 16:52:47.340 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" active endpoints received: "0x01, 0x0A, 0xF2"
2022.10.26 16:52:47.411 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" active endpoints received: "0x01, 0x0A, 0xF2"
2022.10.26 16:52:47.414 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" active endpoints received: "0x01, 0x0A, 0xF2"
2022.10.26 16:52:47.519 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" endpoint "0x01" simple descriptor received
2022.10.26 16:52:47.522 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" endpoint "0x01" simple descriptor received
2022.10.26 16:52:57.957 (wrn) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" interview aborted: "endpoint 0x01 simple descriptor request failed"
2022.10.26 16:52:58.032 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" endpoint "0x0A" simple descriptor received
2022.10.26 16:52:58.035 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" endpoint "0x0A" simple descriptor received
2022.10.26 16:52:58.110 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" endpoint "0xF2" simple descriptor received
2022.10.26 16:52:58.113 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" endpoint "0xF2" simple descriptor received
2022.10.26 16:52:58.194 (wrn) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" model name "PEHPL0X" unrecognized
2022.10.26 16:52:58.197 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" manufacturer name is "Perenio" and model name is "PEHPL0X"
2022.10.26 16:52:58.200 (inf) zigbee:    Device "f4:ce:36:e3:1d:e1:c9:c2" interview finished

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/f2e84a77eb03a1c9f606d67b3a819884181ece9d
