### ISSUE TITLE
сенсор Perenio Motion Sensor PECMS01 после последнего обновления не работает параметр  Occupancy

### ISSUE THREAD

**Issue by cgtut** [u236/homed-service-zigbee#142]
их несколько штук и все сразу перестали работать параметр Occupancy всё время false, 
![chrome_HjCrCMbKXc](https://github.com/u236/homed-service-zigbee/assets/82533683/0facfb1d-ccbc-42a4-96d0-4f949fe488df)
![chrome_KoqUnP19Tj](https://github.com/u236/homed-service-zigbee/assets/82533683/a41b594d-bf38-4292-93c0-35a73c8b3dc3)
![chrome_Ot3juw7NQz](https://github.com/u236/homed-service-zigbee/assets/82533683/cdbf99d3-3d39-44b0-9aaf-980dd65de168)

**Comment by u236** [comment]
в последний раз класс, работающий со свойством occupancy для этих датчиков, менялся почти [2 месяца](https://github.com/u236/homed-service-zigbee/commit/73c8e30075ed157b694560c21c38ca1b85ff9245) назад, сомневаюсь, что проьблема связана с обновленем, я бы попробовал переджойнить один из датчиков, а заодно прислать сюда лог интервью

**Comment by cgtut** [comment]
пробовал переджойнить , с 3 раза заработал 1 из 3х, мучался  , потом переустановил homed на переньке всё заработало
