### ISSUE TITLE
Добавить поддержку eWeLink/SA-003-Zigbee

### ISSUE THREAD

**Issue by RavenHuginn** [u236/homed-service-zigbee#143]
Прошу добавить поддержку eWeLink/SA-003-Zigbee мне он пришёл в виде стика как "**Усилитель сигнала для eWeLink ZigBee 3,0 USB**".
Умеет быть роутером и включать выключать LED распаяный на нём :)

У меня заработало при добавлении этого кода:
`    {
      "description":    "eWeLink/SA-003-Zigbee",
      "modelNames":     ["SA-003-Zigbee"],
      "properties":     ["status"],
      "actions":        ["status"],
      "bindings":       ["status"],
      "exposes":        ["switch"]
    }	`
в файл sonoff.json

![image](https://github.com/u236/homed-service-zigbee/assets/20950826/5a7a02a9-6ff2-4c0b-8066-833912affcd6)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/1ed99075f0e1a215e6c4a5b619df63ea2856d1ce
