### ISSUE TITLE
Zigbee реле _TZ3000_kqvb5akv/TS0001 в подрозетник Not Supported, но работает

### ISSUE THREAD

**Issue by yaadyaad** [u236/homed-service-zigbee#145]
_TZ3000_kqvb5akv/TS0001

<img width="585" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/0938c77f-5d45-455f-992c-eb5269c49bd5">

```json
{
  "active": true,
  "cloud": false,
  "description": "_TZ3000_kqvb5akv/TS0001",
  "discovery": true,
  "endpoints": [
    {
      "deviceId": 256,
      "endpointId": 1,
      "inClusters": [
        3,
        4,
        5,
        6,
        1794,
        2820,
        57344,
        57345,
        0
      ],
      "outClusters": [
        25,
        10
      ],
      "profileId": 260
    },
    {
      "deviceId": 97,
      "endpointId": 242,
      "outClusters": [
        33
      ],
      "profileId": 41440
    }
  ],
  "ieeeAddress": "a4:c1:38:ce:62:22:00:fa",
  "interviewFinished": true,
  "lastSeen": 1710855258,
  "linkQuality": 87,
  "logicalType": 1,
  "manufacturerCode": 4417,
  "manufacturerName": "_TZ3000_kqvb5akv",
  "modelName": "TS0001",
  "name": "BalconyPower",
  "networkAddress": 44848,
  "powerSource": 1,
  "supported": false,
  "version": 72
}


```

**Comment by yaadyaad** [comment]
Добавил в tyua.json следующий раздел, по аналогии с предыдущими примерами.

```json
    {
      "description":    "TUYA TS0001/TS0011 1-Channel Relay with Power Monitoring",
      "modelNames":     ["_TZ3000_kqvb5akv"],
      "properties":     ["status", "energy", "voltage", "current", "power", "tuyaPowerOnStatus"],
      "actions":        ["status", "tuyaPowerOnStatus"],
      "bindings":       ["status", "energy", "power"],
      "reportings":     ["status", "energy", "voltage", "current", "power"],
      "exposes":        ["switch", "powerOnStatus", "energy", "voltage", "current", "power"],
      "options":        {"powerOnStatus": {"enum": ["off", "on", "previous"]}, "energyDivider": 100, "currentDivider": 1000, "tuyaMagic": true}
    },
```

Девайс стал Supported, значение Energy стало отображаться корректно (раньше было в 10 раз больше). Но перестали отображаться значения Voltage, Current, Power. 

<img width="941" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/839d6c93-6b0b-4fbc-925c-adea34764a85">

Логи Зигбии следующие
<img width="1057" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/f95d2413-55b6-41aa-9b35-948780d49ac6">

Куда копать?

**Comment by yaadyaad** [comment]
Удалил девайс, перестартанул сервис, добавил девайс, все заработало.

<img width="775" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/928763d5-6817-4288-a935-c45e76e8224f">

**Comment by yaadyaad** [comment]
https://github.com/u236/homed-service-zigbee/pull/151

**Comment by n8065** [comment]
Имеются на руках такие же реле, но от PR меня останавливал один нюанс, с которым пока не было времени разбираться.
@yaadyaad, корректно ли отрабатываются команды на включение/выключение/переключение состояния с интерфейса HOMEd? У меня это выглядит так:

https://github.com/u236/homed-service-zigbee/assets/2425177/63924635-d417-4202-9af3-8a55ab70922d

В логах следующее:

```
2024.03.20 07:54:49.422 (inf) zigbee:    Device "relay-pwr" status action request finished successfully
2024.03.20 07:54:49.423 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 111
2024.03.20 07:54:49.477 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 147
2024.03.20 07:54:51.780 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 112
2024.03.20 07:54:51.782 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 113
2024.03.20 07:54:54.908 (inf) zigbee:    Device "relay-pwr" status action request finished successfully
2024.03.20 07:54:54.909 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 114
2024.03.20 07:54:54.969 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 168
2024.03.20 07:54:57.792 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 115
2024.03.20 07:54:57.794 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 116

```

Само реле при этом отрабатывает команды корректно.

**Comment by u236** [comment]
> Само реле при этом отрабатывает команды корректно.

Очень похоже, что дело в отсутствии "волшебного"!запроса во время интервью. В описании устройства есть `"tuyaMagic": true`?

**Comment by n8065** [comment]
Есть.

```
    {
      "description":    "TUYA TS0001 1-Channel Relay with Power Monitoring",
      "modelNames":     ["_TZ3000_kqvb5akv"],
      "properties":     ["status", "energy", "voltage", "current", "power", "tuyaPowerOnStatus"],
      "actions":        ["status", "tuyaPowerOnStatus"],
      "bindings":       ["status", "energy", "power"],
      "reportings":     ["status", "energy", "voltage", "current", "power"],
      "exposes":        ["switch", "powerOnStatus", "energy", "voltage", "current", "power"],
      "options":        {"powerOnStatus": {"enum": ["on", "off", "previous"]}, "energyDivider": 100, "currentDivider": 1000, "tuyaMagic": true}
    },

```

**Comment by yaadyaad** [comment]
Да, отрабатывает корректно. Включается-выключается.
<img width="679" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/37c9b6e0-bc7f-4df2-a809-91ca5d6204a5">
<img width="634" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/3ad9b2a5-c349-4fb9-86f0-72ca2581e1d7">

<img width="1418" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/5a9552cf-aee6-46c5-958e-4d4d1615010b">

Только какое-то свойство не находит
<img width="1314" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/b6135041-14e7-4614-b281-a58ecace6017">

**Comment by yaadyaad** [comment]
<img width="1521" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/3bc86df9-c064-4009-a520-693baa76b05b">

**Comment by n8065** [comment]
@yaadyaad, а в качестве координатора кто? У меня Zigbee V4 (СС2652P2 RF-STAR).

@u236, если это поможет, могу посниффить трафик этой железки в связке с tuya gateway и в связке с HA (координаторы при этом будут другие). Но быстро не обещаю - в будни вряд ли смогу заняться. Вероятнее всего - выходные.

**Comment by yaadyaad** [comment]
@n8065 Координатор это HOMEd Pico
<img width="659" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/e2cb3e18-2746-40ab-a021-62cd43eeefe7">

**Comment by u236** [comment]
> могу посниффить трафик этой железки в связке с tuya gateway и в связке с HA

пока не нужно, я поищу инфу

**Comment by u236** [comment]
> как дебажить такие вещи, чтобы нормально добавлять свойства девайсов

ну так в логах написаны идентификаторы кластеров и атрибутов/команд, проблема тут в том, что китайцы очень любят выходить за рамки стандарта, так что иногда без "родгого" шлюза и сниффера вообще нереально разобоаться

**Comment by yaadyaad** [comment]
а можно ссылочку на правильный реальный родной шлюз? и на сниффер

**Comment by u236** [comment]
> а можно ссылочку на правильный реальный родной шлюз? и на сниффер

в чате спроси, их тыща :)

**Comment by yaadyaad** [comment]
Туя Термостат работает, но тоже в логах ругается на те же самые свойства
<img width="1470" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/e19e7700-2911-4853-a519-b35f0ff164ae">

**Comment by u236** [comment]
> ругается на те же самые свойства
это проприетарные туевские атрибуты неизвестного назначения, просто забей :) и перестань кидать логи картинками

**Comment by u236** [comment]
Что касается глюка с "промаргиваванием", у меня есть подозрение, что проблема в чтении атрибута сразу после выполнения действия. Вероятно, по какой-то причине, девайс в ответ на чтение отдает старое значение атрибута, проверить это можно, если закомментировать вот эти строки:
https://github.com/u236/homed-service-zigbee/blob/2cb671aac28b1f3eb3d50347afeff3a7f49dfb66/zigbee.cpp#L1756-L1757

Проверьте кто-нибудь, если проканает, добавлю опцию.

**Comment by n8065** [comment]
> Что касается глюка с "промаргиваванием", у меня есть подозрение, что проблема в чтении атрибута сразу после выполнения действия. 
> ...
> Проверьте кто-нибудь, если проканает, добавлю опцию.

Подтверждаю. После 8-10 тычков on/off промаргивания не наблюдал:

```
2024.03.20 15:47:21.139 (inf) zigbee:    Device "relay-pwr" status action request (6b) finished successfully
2024.03.20 15:47:21.181 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 254
2024.03.20 15:47:23.778 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 255
2024.03.20 15:47:23.780 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 0

2024.03.20 15:47:30.771 (inf) zigbee:    Device "relay-pwr" status action request (75) finished successfully
2024.03.20 15:47:30.816 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 1
2024.03.20 15:47:33.781 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 2
2024.03.20 15:47:33.783 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 3
```

> А еще, для подтверждения догадки, можно добавить вывод идентификатора запроса вот тут:
> ...
> В этом случае будет понятно, какой конкретно ответ приходит на запрос чтения атрибута.

Отправлялись запросы "on", затем "off":
_(в этом выводе есть "моргания" по той причине, что стачала проверялось второе предложение, а затем первое, вывод которого выше)_
```
2024.03.20 15:39:35.960 (inf) zigbee:    Device "relay-pwr" status action request (64) finished successfully
2024.03.20 15:39:36.016 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 221
2024.03.20 15:39:36.017 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 101
2024.03.20 15:39:38.371 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 222
2024.03.20 15:39:38.373 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 223

2024.03.20 15:39:43.593 (inf) zigbee:    Device "relay-pwr" status action request (74) finished successfully
2024.03.20 15:39:43.630 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 224
2024.03.20 15:39:43.654 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "01" and transaction id 117
2024.03.20 15:39:46.384 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 225
2024.03.20 15:39:46.386 (inf) zigbee:    Device "relay-pwr" endpoint "0x01" cluster "0x0006" attribute "0x0000" report received with type "0x10" and data "00" and transaction id 226
```

**Comment by u236** [comment]
> в этом выводе есть "моргания"

да, по логу видно, что именно в ответ на запрос чтения атрибута приходит ответ со старым состоянием, сегодня чуть позже добавлю опцию тогда, для запрета этого самого чтения

**Comment by yaadyaad** [comment]
Да, я поставил wireshark. Если девайс включен - сначала уходит команда выключить. Затем интерфейс пользователя сразу отображает выключенный статус (серая иконка). Затем девайс присылает статус, что он пока еще On, интерфейс его включает обратно. И потом через 1 сек девай выключается, присылает статус Off. И тогда уже на интерфейсе он выключается. 

То есть надо на интерфейсе не менять состояние самостоятельно, все изменения через mqtt должны приходить.

**Comment by u236** [comment]
> То есть надо на интерфейсе не менять состояние самостоятельно, все изменения через mqtt должны приходить

Там ничего и не меняется самостоятельно, проблема в том что устройство присылает новое состояние после запроса, а в ответ на чтение состояния присылает старое.

Короче говоря, нечего тут думать: https://github.com/u236/homed-service-zigbee/commit/5f3a2049b0ffffa69ef7e5153adebb219b0818de.

@n8065, добавь в опции устройства `"skipAttributeRead": true` и если все заработает как надо, я ближе к вечеру смержу PR.

**Comment by u236** [comment]
Наконец-то нормальное issue с бурной дискуссией, как во взрослых репозиториях :)
Спасибо, ребята!

**Comment by n8065** [comment]
> @n8065, добавь в опции устройства `"skipAttributeRead": true` и если все заработает как надо, я ближе к вечеру смержу PR.

Собрал свежий бинарник, проверил без опции и с ней - работает.

Спасибо за отзывчивость и оперативность!
