### ISSUE TITLE
Zigbee датчик температуры и влажности eWeLink/SNZB-02P - Not Supported, но работает

### ISSUE THREAD

**Issue by yaadyaad** [u236/homed-service-zigbee#147]
<img width="504" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/66372856-fc7d-4dc5-a0e0-dff6271ef564">

```json
{
  "active": true,
  "cloud": false,
  "description": "eWeLink/SNZB-02P",
  "discovery": true,
  "endpoints": [
    {
      "deviceId": 770,
      "endpointId": 1,
      "inClusters": [
        0,
        1,
        3,
        32,
        1026,
        1029,
        64599,
        64529
      ],
      "outClusters": [
        25
      ],
      "profileId": 260
    }
  ],
  "firmware": "2.1.0",
  "ieeeAddress": "34:10:f4:ff:fe:fa:d0:48",
  "interviewFinished": true,
  "lastSeen": 1710855716,
  "linkQuality": 21,
  "logicalType": 2,
  "manufacturerCode": 4742,
  "manufacturerName": "eWeLink",
  "modelName": "SNZB-02P",
  "name": "BalconyTempHumidity",
  "networkAddress": 11082,
  "powerSource": 3,
  "supported": false
}
```

**Comment by yaadyaad** [comment]
https://www.zigbee2mqtt.io/devices/SNZB-02P.html

**Comment by yaadyaad** [comment]
Добавил в sonoff.json по аналогии поддержку устройства. Строка 29 и далее. Пользовался описанием устройства тут https://www.zigbee2mqtt.io/devices/SNZB-02P.html . Почему-то пропала батарея.

```json
    {
      "description":    "Sonoff Temperature and Humidity Sensor SNZB-02P",
      "modelNames":     ["SNZB-02P"],
      "properties":     ["batteryPercentage", "temperature", "humidity", "voltage"],
      "bindings":       ["battery", "temperature", "humidity"],
      "reportings":     ["batteryPercentage", "temperature", "humidity", "voltage"],
      "exposes":        ["battery", "batteryPercentage" ,"temperature", "humidity", "voltage", "temperatureCalibration", "temperaturePrecision", "humidityCalibration", "humidityPrecision"],
      "options": {
        "temperatureCalibration": {"min": -30, "max": 30},
        "temperaturePrecision": {"min": 0, "max": 3},
        "humidityCalibration": {"min": -30, "max": 30},
        "humidityPrecision": {"min": 0, "max": 3}
      }
    },
```
Поэтому пока пул-реквест не делаю. 

<img width="905" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/60e29fc3-4e13-4e9f-ac7d-7891f3c3f724">

**Comment by yaadyaad** [comment]
<img width="1576" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/5c844876-d82a-44da-bbe6-33fa911235b9">

**Comment by yaadyaad** [comment]
<img width="1262" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/d039d628-c0c2-41c8-9850-fecee7137128">

**Comment by yaadyaad** [comment]
<img width="1648" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/ce62bbc8-de3b-4031-b14d-42e44e98de63">

**Comment by yaadyaad** [comment]
Battery подтянулась, а остального похоже нет в девайсе, хотя я брал название свойств из m2z
<img width="479" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/905971/263b5404-0843-4073-b88e-e6cabc9359bb">

**Comment by u236** [comment]
очень много лишнего понаписал :) то что ты принял за настройки корректировок показателей на самом деле индивидуальные настройки репортига (непонятно зачем), а так этот датчик, судя по всему вообще ничем не отличается от своего старшего брата `SNZB-02`, так что пусть будет вот так: https://github.com/u236/homed-service-zigbee/commit/015148c46503ae19654691d94358511bb02fec43
