### ISSUE TITLE
Wall Switch 2 Gang Tuya _TZ3000_18ejxno0

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#15]
https://aliexpress.ru/item/1005002638421893.html

2022.10.26 16:55:13.785 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" joined network with address "0x5C98"
2022.10.26 16:55:13.788 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" rejoined network with address "0x5C98"
2022.10.26 16:55:14.323 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" node descriptor received, manufacturer code: "0x1141"
2022.10.26 16:55:14.326 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" node descriptor received, manufacturer code: "0x1141"
2022.10.26 16:55:14.537 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" active endpoints received: "0x01, 0x02"
2022.10.26 16:55:14.541 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" active endpoints received: "0x01, 0x02"
2022.10.26 16:55:15.164 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" endpoint "0x01" simple descriptor received
2022.10.26 16:55:15.167 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" endpoint "0x01" simple descriptor received
2022.10.26 16:55:15.374 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" endpoint "0x02" simple descriptor received
2022.10.26 16:55:15.377 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" endpoint "0x02" simple descriptor received
2022.10.26 16:55:16.012 (wrn) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" model name "_TZ3000_18ejxno0" unrecognized
2022.10.26 16:55:16.015 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" manufacturer name is "TUYA" and model name is "_TZ3000_18ejxno0"
2022.10.26 16:55:16.018 (inf) zigbee:    Device "a4:c1:38:17:d5:04:ae:01" interview finished

**Comment by u236** [comment]
Added in https://github.com/u236/homed-service-zigbee/commit/28aeb9e8c241788670b4de33044538ac4e303d05.
