### ISSUE TITLE
Aqara FP1 Presence Detector RTCZCGQ11LM неправильно работает в версии ХЗ 3,7.1 и выше

### ISSUE THREAD

**Issue by Sborkahome** [u236/homed-service-zigbee#157]
Начиная с версии 3,7.1 неверно работает датчик:
1) не устанавливаются значения  sensitivityMode, distanceMode, detectionMode, Reset presence (в топик td из даша прилетают задаваемые значения. а в топике fd эти параметры остаются в значении NULL, в даше, соответственно, всё в NULL, в логах тишина);
2) параметр Occupancy при обноружении объекта устанавливается в значение true, после того, как объект не обнаружен, устанавливается  в false (как и должно быть), но затем, в течение одной-двух минут, самопроизвольно устанавливается в значение true.
Проверил работу датчика в версии 3,7,0 - все норм, параметры устанавливаются, в лог пишутся, переключения из falsa в true - нет.
Почините, пожалуйста.

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/fc5ae693fb661df31a9ecfd2b793a74f7729c181
