### ISSUE TITLE
Siren NEO Tuya (_TZE200_t1blo2bj)

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#16]
https://aliexpress.ru/item/1005003610700155.html

2022.10.26 16:58:10.864 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" joined network with address "0x3BF5"
2022.10.26 16:58:10.868 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" rejoined network with address "0x3BF5"
2022.10.26 16:58:10.946 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" is router
2022.10.26 16:58:10.949 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" node descriptor received, manufacturer code: "0x1141"
2022.10.26 16:58:10.952 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" is router
2022.10.26 16:58:10.955 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" node descriptor received, manufacturer code: "0x1141"
2022.10.26 16:58:11.027 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" active endpoints received: "0x01, 0xF2"
2022.10.26 16:58:11.030 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" active endpoints received: "0x01, 0xF2"
2022.10.26 16:58:11.105 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" simple descriptor received
2022.10.26 16:58:11.108 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" simple descriptor received
2022.10.26 16:58:11.193 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" endpoint "0xF2" simple descriptor received
2022.10.26 16:58:11.196 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" endpoint "0xF2" simple descriptor received
2022.10.26 16:58:11.254 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" endpoint "0xF2" simple descriptor received
2022.10.26 16:58:11.258 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" endpoint "0xF2" simple descriptor received
2022.10.26 16:58:11.339 (wrn) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" model name "_TZE200_t1blo2bj" unrecognized
2022.10.26 16:58:11.342 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" manufacturer name is "TUYA" and model name is "_TZE200_t1blo2bj"
2022.10.26 16:58:11.345 (inf) zigbee:    Device "a4:c1:38:8e:c5:56:74:47" interview finished
2022.10.26 16:58:17.287 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x11" with payload "00:0a:42"
2022.10.26 16:58:17.290 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x11" with payload "00:0a:42"
2022.10.26 16:58:17.411 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x01" with payload "00:0b:05:04:00:01:02"
2022.10.26 16:58:17.414 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x01" with payload "00:0b:05:04:00:01:02"
2022.10.26 16:58:17.610 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x01" with payload "00:0c:07:02:00:04:00:00:00:0a"
2022.10.26 16:58:17.614 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x01" with payload "00:0c:07:02:00:04:00:00:00:0a"
2022.10.26 16:58:17.811 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x01" with payload "00:0d:0f:02:00:04:00:00:00:64"
2022.10.26 16:58:17.814 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x01" with payload "00:0d:0f:02:00:04:00:00:00:64"
2022.10.26 16:58:18.012 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x01" with payload "00:0e:15:04:00:01:05"
2022.10.26 16:58:18.015 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0xEF00" command "0x01" with payload "00:0e:15:04:00:01:05"
2022.10.26 16:58:22.542 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0x0000" attribute "0xFFE2" with data type "0x20" and data "30"
2022.10.26 16:58:22.546 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0x0000" attribute "0xFFE4" with data type "0x20" and data "01"
2022.10.26 16:58:22.549 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0x0000" attribute "0xFFE2" with data type "0x20" and data "30"
2022.10.26 16:58:22.552 (wrn) zigbee:    No property found for device "a4:c1:38:8e:c5:56:74:47" endpoint "0x01" cluster "0x0000" attribute "0xFFE4" with data type "0x20" and data "01"

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/db1ed02b5ce411db3d937f478e01760b6de3a444
