### ISSUE TITLE
Добавление опции "Не беспокоить"(Do not disturb) в лампы eWeLink

### ISSUE THREAD

**Issue by RavenHuginn** [u236/homed-service-zigbee#161]
Прошу рассмотреть возможность добавления опции "Не беспокоить"(Do not disturb) в лампы CK-BL702-AL-01 (7009_Z102LG03-1) 
В активированном состоянии не включает лампы после отключения/включения электропитания.

![image](https://github.com/u236/homed-service-zigbee/assets/20950826/d06d6ea4-a454-47de-b4c1-729785d268d8)

https://www.zigbee2mqtt.io/devices/CK-BL702-AL-01.html

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/28136ccaedb17649732215582692efb1dac09d7b, прошу протестировать, для этого нужно:
1. обновить пакет `homed-common` до версии 1.0.3
2. обновить бинарник из [песочницы](http://sandbox.u236.org/homed-zigbee/)
3. обновить [other.json](https://raw.githubusercontent.com/u236/homed-service-zigbee/master/deploy/data/usr/share/homed-zigbee/other.json)
