### ISSUE TITLE
Датчик дыма

### ISSUE THREAD

**Issue by Spytnik1265** [u236/homed-service-zigbee#164]
Прошу добавить поддержку датчика дыма
![Screenshot_20240417-211211](https://github.com/u236/homed-service-zigbee/assets/136011966/41480d15-dfa3-40aa-aa84-36bc61945d7f)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/8e5d274d91fc9e96edb9f037055c0fb1a487d595
на будущее - хотябы модель буквами пишите, чтоб не приходилось с картинки перепечатывать
