### ISSUE TITLE
Добавить поддержку EfektaLab/EFEKTA_AQ_Smart_Monitor

### ISSUE THREAD

**Issue by vadimnpechorin** [u236/homed-service-zigbee#165]
![EFEKTA_AQ_Smart_Monitor](https://github.com/u236/homed-service-zigbee/assets/79060870/cca4ac8e-4021-49f8-bb13-dc7f3278b299)

**Устройство:** https://telegra.ph/Datchik-uglekislogo-gaza-i-letuchih-organicheskih-soedinenij-EFEKTA-AQ-Smart-Monitor--Zigbee-30-04-21
**Конвертер:** https://github.com/smartboxchannel/EFEKTA-CO2-Smart-Monitor-V3/blob/main/z2m_converter/EFEKTA_AQ_Smart_Monitor_R3.js

**Device info:** [EFEKTA_AQ_Smart_Monitor.json](https://github.com/u236/homed-service-zigbee/files/15108099/EFEKTA_AQ_Smart_Monitor.json)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/ae07b48a4447863f32c9bf66b728c5c40d7a7999
