### ISSUE TITLE
Доброго дня. Добавить по возможности поддержку eWeLink/SNZB-01P

### ISSUE THREAD

**Issue by Poznavhiy** [u236/homed-service-zigbee#168]
![image](https://github.com/u236/homed-service-zigbee/assets/85444561/0201a948-2946-4e0d-9e07-bdb228a5c1fd)

{
  "active": true,
  "cloud": true,
  "description": "eWeLink/SNZB-01P",
  "discovery": true,
  "endpoints": [
    {
      "deviceId": 0,
      "endpointId": 1,
      "inClusters": [
        0,
        1,
        3,
        32,
        64599
      ],
      "outClusters": [
        3,
        6,
        25
      ],
      "profileId": 260
    }
  ],
  "firmware": "2.2.0",
  "ieeeAddress": "0c:ae:5f:ff:fe:aa:82:b7",
  "interviewFinished": true,
  "lastSeen": 1715620882,
  "linkQuality": 156,
  "logicalType": 2,
  "manufacturerCode": 4742,
  "manufacturerName": "eWeLink",
  "modelName": "SNZB-01P",
  "name": "Zvonok",
  "networkAddress": 40386,
  "powerSource": 0,
  "supported": false
}

Спасибо

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/7735cfbbf731a815972fc6ea024a8f345f9006a3
