### ISSUE TITLE
Aqara Opple 6 buttons

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#17]
2022.10.26 17:12:03.160 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" joined network with address "0x9736"
2022.10.26 17:12:03.163 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" rejoined network with address "0x9736"
2022.10.26 17:12:03.650 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" node descriptor received, manufacturer code: "0x115F"
2022.10.26 17:12:03.653 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" node descriptor received, manufacturer code: "0x115F"
2022.10.26 17:12:03.962 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" active endpoints received: "0x01, 0x02, 0x03, 0x04, 0x05, 0x06"
2022.10.26 17:12:03.965 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" active endpoints received: "0x01, 0x02, 0x03, 0x04, 0x05, 0x06"
2022.10.26 17:12:06.939 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" simple descriptor received
2022.10.26 17:12:06.942 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" simple descriptor received
2022.10.26 17:12:26.956 (wrn) zigbee:    Device "54:ef:44:10:00:17:a8:1d" interview timed out
2022.10.26 17:12:26.959 (wrn) zigbee:    Device "54:ef:44:10:00:17:a8:1d" interview timed out
2022.10.26 17:12:42.517 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" left network
2022.10.26 17:12:57.733 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" joined network with address "0x0794"
2022.10.26 17:12:57.737 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" rejoined network with address "0x0794"
2022.10.26 17:12:58.248 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" node descriptor received, manufacturer code: "0x115F"
2022.10.26 17:12:58.252 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" node descriptor received, manufacturer code: "0x115F"
2022.10.26 17:12:58.532 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" node descriptor received, manufacturer code: "0x115F"
2022.10.26 17:12:58.535 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" node descriptor received, manufacturer code: "0x115F"
2022.10.26 17:13:01.495 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" active endpoints received: "0x01"
2022.10.26 17:13:01.499 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" active endpoints received: "0x01"
2022.10.26 17:13:02.712 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" simple descriptor received
2022.10.26 17:13:02.715 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" simple descriptor received
2022.10.26 17:13:03.933 (wrn) zigbee:    Device "54:ef:44:10:00:17:a8:1d" model name "lumi.remote.b686opcn01" unrecognized
2022.10.26 17:13:03.936 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" manufacturer name is "LUMI" and model name is "lumi.remote.b686opcn01"
2022.10.26 17:13:03.939 (inf) zigbee:    Device "54:ef:44:10:00:17:a8:1d" interview finished
2022.10.26 17:13:03.990 (wrn) zigbee:    No property found for device "00:15:8d:00:00:da:9f:12" endpoint "0x01" cluster "0x0402" attribute "0x0000" with data type "0x29" and data "a5:09"
2022.10.26 17:13:03.994 (wrn) zigbee:    No property found for device "00:15:8d:00:00:da:9f:12" endpoint "0x01" cluster "0x0402" attribute "0x0001" with data type "0x29" and data "dd:12"
2022.10.26 17:13:03.997 (wrn) zigbee:    No property found for device "00:15:8d:00:00:da:9f:12" endpoint "0x01" cluster "0x0402" attribute "0x0002" with data type "0x29" and data "45:03"
2022.10.26 17:13:04.000 (wrn) zigbee:    No property found for device "00:15:8d:00:00:da:9f:12" endpoint "0x01" cluster "0x0402" attribute "0x0003" with data type "0x21" and data "42:00"
2022.10.26 17:13:04.004 (wrn) zigbee:    No property found for device "00:15:8d:00:00:da:9f:12" endpoint "0x01" cluster "0x0402" attribute "0x0000" with data type "0x29" and data "a5:09"
2022.10.26 17:13:04.007 (wrn) zigbee:    No property found for device "00:15:8d:00:00:da:9f:12" endpoint "0x01" cluster "0x0402" attribute "0x0001" with data type "0x29" and data "dd:12"
2022.10.26 17:13:04.010 (wrn) zigbee:    No property found for device "00:15:8d:00:00:da:9f:12" endpoint "0x01" cluster "0x0402" attribute "0x0002" with data type "0x29" and data "45:03"
2022.10.26 17:13:04.014 (wrn) zigbee:    No property found for device "00:15:8d:00:00:da:9f:12" endpoint "0x01" cluster "0x0402" attribute "0x0003" with data type "0x21" and data "42:00"

2022.10.26 17:13:33.245 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0006" command "0x00" with payload "02"
2022.10.26 17:13:33.248 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0006" command "0x00" with payload "02"
2022.10.26 17:13:35.464 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0006" command "0x01" with payload "02"
2022.10.26 17:13:35.467 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0006" command "0x01" with payload "02"
2022.10.26 17:13:36.781 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0008" command "0x02" with payload "00:55:07:00:00:00:02"
2022.10.26 17:13:36.784 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0008" command "0x02" with payload "00:55:07:00:00:00:02"
2022.10.26 17:13:37.941 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0008" command "0x02" with payload "01:55:07:00:00:00:02"
2022.10.26 17:13:37.944 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0008" command "0x02" with payload "01:55:07:00:00:00:02"
2022.10.26 17:13:39.031 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0300" command "0x4C" with payload "01:45:00:07:00:00:00:00:00:00:00:02"
2022.10.26 17:13:39.035 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0300" command "0x4C" with payload "01:45:00:07:00:00:00:00:00:00:00:02"
2022.10.26 17:13:40.468 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0300" command "0x4C" with payload "01:45:00:07:00:00:00:00:00:00:00:02"
2022.10.26 17:13:40.472 (wrn) zigbee:    No property found for device "54:ef:44:10:00:17:a8:1d" endpoint "0x01" cluster "0x0300" command "0x4C" with payload "01:45:00:07:00:00:00:00:00:00:00:02"

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/c9967653ba31ff735e4a468b32d0c320bb93ac42
