### ISSUE TITLE
Добавить поддержку "_TZE204_cjbofhxw"

### ISSUE THREAD

**Issue by yser1** [u236/homed-service-zigbee#177]
День добрый, прошу добавить поддержку бесконтактного энергомониторинга на одну фазу 
![Screenshot 2024-06-03 at 10-43-02 HOMEd](https://github.com/u236/homed-service-zigbee/assets/73287495/85205a3f-c861-4525-9ece-1cc4b98d3e38)

{
  "active": true,
  "cloud": false,
  "description": "_TZE204_cjbofhxw/TS0601",
  "discovery": false,
  "endpoints": [
    {
      "deviceId": 81,
      "endpointId": 1,
      "inClusters": [
        0,
        4,
        5,
        61184
      ],
      "outClusters": [
        25,
        10
      ],
      "profileId": 260
    }
  ],
  "ieeeAddress": "38:39:8f:ff:fe:8d:e8:f8",
  "interviewFinished": true,
  "lastSeen": 1717396971,
  "linkQuality": 112,
  "logicalType": 1,
  "manufacturerCode": 4098,
  "manufacturerName": "_TZE204_cjbofhxw",
  "modelName": "TS0601",
  "neighbors": [
    {
      "linkQuality": 154,
      "networkAddress": 0
    },
    {
      "linkQuality": 82,
      "networkAddress": 26621
    }
  ],
  "networkAddress": 38687,
  "powerSource": 1,
  "supported": false,
  "version": 70,
  "name": "38:39:8f:ff:fe:8d:e8:f8"
}

**Comment by yser1** [comment]
Спасибо за быстрое добавление устройства, но к сожалению данных никаких нет (см. скриншот), сразу писать не стал т.к. устройство на даче, а вот вчера вечером был на даче и думал что удалив и заново добавив устройство данные появятся - не помогло.  Подскажите, может какие логи нужно собрать и прислать?

![Screenshot 2024-06-06 at 10-40-53 HOMEd](https://github.com/u236/homed-service-zigbee/assets/73287495/14fc1af9-c8e8-4ce7-88e2-b8b238e5facb)
?

**Comment by yser1** [comment]
нашел в настройка параметры для лога и включил запись логов zigbee

[homed.log](https://github.com/user-attachments/files/15613215/homed.log)

**Comment by u236** [comment]
> нашел в настройка параметры для лога и включил запись логов zigbee
> 
> 
> 
> [homed.log](https://github.com/user-attachments/files/15613215/homed.log)
> 
> 

Завтра посмотрю или сегодня ближе к ночи. Устройство удаляли перед повторной привязкой? 

Пока предлагаю попробовать добавить в описание устройства опцию `"tuyaMagic": true`, как у некоторых других устройств в  tuya.json, а потом опять перепривязать устройство с удадением.

**Comment by yser1** [comment]
Да, перед привязкой удалял.

Ок, попробою с добавлением опции, но это уже будет в субботу.

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/2110697c8237299e02f1efe9d95c80503a7741b4

**Comment by u236** [comment]
> но это уже будет только в субботу.

привет, удалось проверить?

**Comment by yser1** [comment]
Привет, вот только вернулся. 
Добавлением опции "tuyaMagic": true не помогло. 

[homed.log](https://github.com/user-attachments/files/15753696/homed.log)

![Screenshot 2024-06-09 at 22-34-49 HOMEd](https://github.com/u236/homed-service-zigbee/assets/73287495/f75001cd-267a-4a11-88f8-8907be8f898b)

**Comment by u236** [comment]
> Привет, вот только вернулся. 
> 
> Добавлением опции "tuyaMagic": true не помогло. 
> 
> 
> 
> [homed.log](https://github.com/user-attachments/files/15753696/homed.log)
> 
> 
> 
> 
> 
> 

Вместо лога загружается скриншот. После добавления опциии устройство переподключили? С удалением?

**Comment by yser1** [comment]
Да, устройство переподключал с удалением.

[homed.log](https://github.com/user-attachments/files/15753880/homed.log)

**Comment by u236** [comment]
> Да, устройство переподключал с удалением.
> 
> 
> 
> [homed.log](https://github.com/user-attachments/files/15753880/homed.log)
> 
> 

В таком случае мне жаль, без устройства на руках я больше ничем не могу помочь :(

**Comment by u236** [comment]
нашел вероятный источник проблемы - устройство отправляет запросы на чтение некоего "состояния подключения шлюза к интернету" и ждет ответа, а homed-zigbee, по очевидной причине, не отвечает

добавил формирование ответа в https://github.com/u236/homed-service-zigbee/commit/73d96bb29342deb6812fd88312596869a5713382

просьба взять тестоый бинарник из [песочницы](http://sandbox.u236.org/homed-zigbee/) и проверить на нем, заработало ли устройство (как обычно, с удалением и переподключением)
