### ISSUE TITLE
Добавить поддержку GS/SOHM-I1

### ISSUE THREAD

**Issue by AndreiCh74** [u236/homed-service-zigbee#178]
![photo_2024-06-08_19-56-16](https://github.com/u236/homed-service-zigbee/assets/98027646/cdcea8f3-5d5b-40e7-aad0-5fea8a031b0a)
https://www.zigbee2mqtt.io/devices/SOHM-I1.html

**Comment by AndreiCh74** [comment]
https://www.zigbee2mqtt.io/devices/SOHM-I1.html

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/3fe528e08dd7da5a0a948cf6641ef99db1631f64
