### ISSUE TITLE
Добавить поддержку JetHome/WS7

### ISSUE THREAD

**Issue by vadimnpechorin** [u236/homed-service-zigbee#179]
JetHome/WS7
![jethome_ws7](https://github.com/u236/homed-service-zigbee/assets/79060870/d11f3f40-7d5f-4987-8e3e-19f97015d338)
**Устройство:** https://jethome.ru/ws7
**Конвертер:** https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/jethome.ts

**Device info:** [JetHome_WS7.json](https://github.com/user-attachments/files/15760069/JetHome_WS7.json)

**Comment by u236** [comment]
прошу собрать лог нажатий на клавиши (с вкюченной опцией debug > zigbee = true в конфиге), жалательно с комментариями (нажал то, нажал это)

**Comment by vadimnpechorin** [comment]
Лог нажатий ключей(контактов):
[debug_jethome+_ws7.txt](https://github.com/user-attachments/files/15774661/debug_jethome%2B_ws7.txt)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/061f2a7024bf3ed0d4910035ed8782926046bbc5
