### ISSUE TITLE
Friendly name: помечать устройство как удаленное, но не удалять

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#18]
Сейчас, если переименованное устройство покидает сеть, а потом заново входит в сеть, то friendly name теряется
Хорошо бы, чтобы friendly name заново подцеплялся

**Comment by u236** [comment]
реализовано в https://github.com/u236/homed-service-zigbee/commit/dd384cb9448f3d02dadeef2ef1f64428a0c180f2
