### ISSUE TITLE
не правильное отображение link quality

### ISSUE THREAD

**Issue by bovops** [u236/homed-service-zigbee#181]
Добрый день, link quality отображает не то значение.
Например, есть 2 датчика, подключенные через роутер.
В общем списке и на странице девайса в LQI показывает уровень сигнала до роутера.
<img width="213" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/1391112/0ae7248d-4cfe-4268-a11f-60d3b5faea5f">
<img width="647" alt="image" src="https://github.com/u236/homed-service-zigbee/assets/1391112/da658fd0-2f74-41e2-beb8-4a1f4116fed9">

**Comment by u236** [comment]
Потому что параметр LQI в любом zigbee-сообщенни, полученном координатором, это всегда "last hop" (уровень сигнала между последним отправителем и координататором). Приблизительный уровень сигнала между устройствами и роутерами отображается на карте сети, данные обновляются раз в час.
