### ISSUE TITLE
Добавить поддержку TuYa TS0601_soil

### ISSUE THREAD

**Issue by gDIeMONd** [u236/homed-service-zigbee#183]
Добрый день!
 Прошу добавить TuYa TS0601_soil, датчик влажности почвы

{
  "active": true,
  "cloud": true,
  "description": "_TZE284_g2e6cpnw/TS0601",
  "discovery": true,
  "endpoints": [
    {
      "colorCapabilities": 65535,
      "deviceId": 81,
      "endpointId": 1,
      "inClusters": [
        4,
        5,
        61184,
        0,
        60672
      ],
      "outClusters": [
        25,
        10
      ],
      "profileId": 260
    }
  ],
  "ieeeAddress": "a4:c1:38:05:4c:26:98:63",
  "interviewFinished": true,
  "lastSeen": 1718693204,
  "linkQuality": 255,
  "logicalType": 2,
  "manufacturerCode": 4417,
  "manufacturerName": "_TZE284_g2e6cpnw",
  "modelName": "TS0601",
  "networkAddress": 13131,
  "powerSource": 3,
  "supported": false,
  "version": 77,
  "name": "a4:c1:38:05:4c:26:98:63"
}

[Z2M](https://github.com/Koenkk/zigbee-herdsman-converters/pull/7609)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/83539f0022dcaeaf106636008da9c7baf92c82ed
