### ISSUE TITLE
Добавить полную поддержку термоголовки Aqara SRTS-A01

### ISSUE THREAD

**Issue by DaN66O** [u236/homed-service-zigbee#185]
Добрый день !
Прошу добавить расширенную поддержку термоголовки Aqara E1 Radiator Thermostat SRTS-A01 
Exposes в з2м : 

`setup, climate (occupied_heating_setpoint, local_temperature, system_mode, preset), sensor, external_temperature_input, calibrated, calibrate, child_lock, window_detection, window_open, valve_detection, valve_alarm, away_preset_temperature, voltage, battery, power_outage_count, device_temperature, schedule, schedule_settings, linkquality`

State 
```
{
    "away_preset_temperature": "30.0",
    "battery": 100,
    "calibrated": true,
    "child_lock": true,
    "device_temperature": 24,
    "internal_heating_setpoint": 15,
    "last_seen": "2024-06-24T11:33:51+03:00",
    "linkquality": 102,
    "local_temperature": 23.6,
    "occupied_heating_setpoint": 15,
    "power_outage_count": 39,
    "preset": "manual",
    "schedule": false,
    "schedule_settings": "mon,sun|0:00,21.0|12:00,17.0|18:00,21.0|23:59,21.0",
    "sensor": "external",
    "setup": false,
    "system_mode": "heat",
    "valve_alarm": false,
    "valve_detection": false,
    "voltage": 3000,
    "window_detection": false,
    "window_open": false,
    "calibrate": null,
    "external_temperature_input": null,
    "update": {
        "installed_version": -1,
        "latest_version": -1,
        "state": null
    },
    "update_available": null
}
```
Тема про нее в з2м
https://github.com/Koenkk/zigbee2mqtt/issues/13993

**Comment by u236** [comment]
к сожалению без устройства на руках ничего не получится
