### ISSUE TITLE
Оставлять пользовательское описание (note), настройки discovery, cloud, active при удалении устройства.

### ISSUE THREAD

**Issue by Sheridan** [u236/homed-service-zigbee#186]
Раз удалённые устройства остаются в БД (имя сохраняется), то будет нелишним сохранять и пользовательское описание, а так-же настройки cloud, active, discovery (https://t.me/homed_zigbee/113794 https://t.me/homed_zigbee/131178)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/b7a7f6e04abeb2410f97e95cc29e885dc4583ff2
