### ISSUE TITLE
Life control ptvo_mclh03

### ISSUE THREAD

**Issue by Poznavhiy** [u236/homed-service-zigbee#189]
Добрый день. Не хочет работать чудесная розетка говорит no support, прошита прошивкой рекламированной Северусом 
![IMG_20240707_191944](https://github.com/u236/homed-service-zigbee/assets/85444561/a516d3f3-6e59-4610-aec4-3cbfe1d09c0f)

**Comment by u236** [comment]
Привет, уточни пожалуйста, чтт именно не работает? Кроме некорректных показателей напяжения/тока.

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/7b9c42b4b2b3bb74d238f241052a009160115455
