### ISSUE TITLE
Добавить поддержку одноклавишного MOES Ring

### ISSUE THREAD

**Issue by RavenHuginn** [u236/homed-service-zigbee#190]
Прошу добавить поддержку одноклавишного выключателя MOES Ring (Tuya)

![image](https://github.com/user-attachments/assets/810b1587-d1b7-4b6b-b5b2-64040b1a2401)

,
	{
      "description":    "_TZ3000_j8dbnrgx/TS0001",
      "modelNames":     ["_TZ3000_j8dbnrgx"],
      "properties":     ["status", "tuyaIndicatorMode", "tuyaPowerOnStatus"],
      "actions":        ["status", "tuyaIndicatorMode", "tuyaPowerOnStatus"],
      "bindings":       ["status"],
      "exposes":        ["switch", "indicatorMode", "powerOnStatus"],
      "options":        {"powerOnStatus": {"enum": ["off", "on", "previous"]}, "tuyaMagic": true}
    }

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/6fdac76c2adb91acb7d318a53c9d08e88fcebfa2
