### ISSUE TITLE
Прошу добавить сирену NAS-AB02B0 в поддержку 

### ISSUE THREAD

**Issue by HomeNV** [u236/homed-service-zigbee#192]
Tuya Neo Temperature & humidity sensor and alarm

![2024-07-21_110818](https://github.com/user-attachments/assets/a9cfea88-001a-40dc-88f7-0e6f69344e25)

{
  "active": true,
  "cloud": true,
  "description": "_TZE200_d0yu2xgi/TS0601",
  "discovery": true,
  "endpoints": [
    {
      "colorCapabilities": 65535,
      "deviceId": 81,
      "endpointId": 1,
      "inClusters": [
        0,
        4,
        5,
        61184
      ],
      "outClusters": [
        25,
        10
      ],
      "profileId": 260
    }
  ],
  "ieeeAddress": "80:4b:50:ff:fe:04:70:30",
  "interviewFinished": true,
  "lastSeen": 1721548563,
  "linkQuality": 131,
  "logicalType": 2,
  "manufacturerCode": 4098,
  "manufacturerName": "_TZE200_d0yu2xgi",
  "modelName": "TS0601",
  "name": "sirena",
  "networkAddress": 53469,
  "powerSource": 3,
  "supported": false,
  "version": 85
}

https://aliexpress.ru/item/1005004158376970.html

https://www.zigbee2mqtt.io/devices/NAS-AB02B0.html#neo-nas-ab02b0

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/e597d2f27e01e141cf4d96390446bae4400457a6
