### ISSUE TITLE
добавить в поддержку TexasInstruments/ti.router

### ISSUE THREAD

**Issue by HomeNV** [u236/homed-service-zigbee#193]
![ti_router](https://github.com/user-attachments/assets/82a2d16f-8170-46b6-824f-872258d9a21e)

{
  "active": true,
  "cloud": true,
  "description": "TexasInstruments/ti.router",
  "discovery": true,
  "endpoints": [
    {
      "colorCapabilities": 65535,
      "deviceId": 255,
      "endpointId": 8,
      "inClusters": [
        0,
        3
      ],
      "outClusters": [
        0
      ],
      "profileId": 260
    },
    {
      "colorCapabilities": 65535,
      "deviceId": 97,
      "endpointId": 242,
      "outClusters": [
        33
      ],
      "profileId": 41440
    }
  ],
  "firmware": "20221102",
  "ieeeAddress": "00:12:4b:00:2a:99:55:84",
  "interviewFinished": true,
  "lastSeen": 1721553087,
  "linkQuality": 142,
  "logicalType": 1,
  "manufacturerCode": 0,
  "manufacturerName": "TexasInstruments",
  "modelName": "ti.router",
  "networkAddress": 27060,
  "powerSource": 1,
  "supported": false,
  "name": "00:12:4b:00:2a:99:55:84"
}

![ti_router1](https://github.com/user-attachments/assets/c9d67646-7b6d-4e86-93da-67a7e7861799)

https://www.zigbee2mqtt.io/devices/ti.router.html#custom%2520devices%2520(diy)-ti.router

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/5cde0d5e13e3271215959cbcebbe424b036a6c19
