### ISSUE TITLE
добавить в поддержку датчик EFEKTA-TH-v1

### ISSUE THREAD

**Issue by HomeNV** [u236/homed-service-zigbee#194]
https://github.com/smartboxchannel/EFEKTA-TH-v1
https://aliexpress.ru/item/1005006146293160.html

![EFEKTA_TH_1](https://github.com/user-attachments/assets/523d3d6e-6e07-457b-9327-4d4e9801acf5)
![EFEKTA_TH_2](https://github.com/user-attachments/assets/985212eb-b6a7-4bbc-b766-81f67ae7862c)
![EFEKTA_TH_3](https://github.com/user-attachments/assets/b664b090-972c-4012-b659-49637cb662b5)

![EFEKTA_TH](https://github.com/user-attachments/assets/8af1958a-4e1e-41a4-90f1-6a827bc73b1c)

почему то не подключается к HOMEd совсем

**Comment by u236** [comment]
> почему то не подключается к HOMEd совсем

чтобы понять, почему не подключается, нужен лог интервью, хотя бы

**Comment by HomeNV** [comment]
> > почему то не подключается к HOMEd совсем
> 
> чтобы понять, почему не подключается, нужен лог интервью, хотя бы

00:12:4b:00:27:2c:f8:10  

[homed.log](https://github.com/user-attachments/files/16345528/homed.log)

**Comment by u236** [comment]
похоже, что устройство спит или еще по какой-то причине не может ответить на запросы во время интервью

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/c67908b9379ff838e408e44271519cf9a7ba5824
