### ISSUE TITLE
прошу добавить в поддержку 1 канал. выключатель

### ISSUE THREAD

**Issue by HomeNV** [u236/homed-service-zigbee#195]
_TZ3000_gidy6sjs/TS0001  Tuya 1 gang switch with N  Avatto

https://aliexpress.ru/item/1005002199687660.html

![tuya_1ch](https://github.com/user-attachments/assets/b1b83a2b-2bde-419f-8656-d5f729aa7719)

{
  "active": true,
  "cloud": true,
  "description": "_TZ3000_gidy6sjs/TS0001",
  "discovery": true,
  "endpoints": [
    {
      "colorCapabilities": 65535,
      "deviceId": 256,
      "endpointId": 1,
      "inClusters": [
        0,
        3,
        4,
        5,
        6,
        57344,
        57345
      ],
      "outClusters": [
        25,
        10
      ],
      "profileId": 260
    },
    {
      "colorCapabilities": 65535,
      "deviceId": 97,
      "endpointId": 242,
      "outClusters": [
        33
      ],
      "profileId": 41440
    }
  ],
  "ieeeAddress": "cc:86:ec:ff:fe:3c:c3:74",
  "interviewFinished": true,
  "lastSeen": 1721668138,
  "linkQuality": 105,
  "logicalType": 1,
  "manufacturerCode": 4098,
  "manufacturerName": "_TZ3000_gidy6sjs",
  "modelName": "TS0001",
  "name": "bathroom_sw",
  "neighbors": [
    {
      "linkQuality": 39,
      "networkAddress": 4764
    },
  ],
  "networkAddress": 28666,
  "powerSource": 1,
  "supported": false,
  "version": 69
}

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/23750053a04863360ade6b8522ef5987f4d2cedd
