### ISSUE TITLE
Добавить в поддержку Aqara  Curtain driver E1 ( ZNCLBL01LM )

### ISSUE THREAD

**Issue by DaN66O** [u236/homed-service-zigbee#196]
Прошу добавить в поддержку мотор aqara для штор.
![Screenshot_5](https://github.com/user-attachments/assets/9e158b55-43c7-4568-8c32-6d9321ba0001)

https://www.zigbee2mqtt.io/devices/ZNCLBL01LM.html#aqara-znclbl01lm

Exposes:
`cover (state, position), hand_open, limits_calibration, battery, voltage, device_temperature, illuminance_lux, motor_state, running, hooks_lock, hooks_state, target_position, power_source, charging, action, linkquality`

State:
```
{
    "battery": 82,
    "charging": false,
    "device_temperature": 27,
    "hand_open": true,
    "hooks_lock": "LOCK",
    "hooks_state": "locked",
    "illuminance_lux": 100,
    "last_seen": "2024-07-24T17:09:35+03:00",
    "linkquality": 0,
    "motor_state": "stopped",
    "position": 100,
    "power_outage_count": 0,
    "power_source": "battery",
    "running": false,
    "state": "OPEN",
    "target_position": 100,
    "update": {
        "installed_version": 6939,
        "latest_version": 6168,
        "state": "idle"
    },
    "voltage": 3000,
    "action": null,
    "update_available": null
}
```
Clusters 
![Screenshot_4](https://github.com/user-attachments/assets/69450a1c-c9a5-4dac-bbe9-b5adc781ae62)

**Comment by u236** [comment]
Увы, этот привод для штор такой же хитрый, как и треклятая термоголовка, поэтому я не могу добавить полную поддержку, не имея устройства на руках. Пока добавил базовый функционал (управление открытием/закрытием и калибровка), надеюсь хотя бы эти функции будут работать. Больше ничем пока не могу помочь, к сожалению.

https://github.com/u236/homed-service-zigbee/commit/3c014c6fff1a51147e5d8b4110136a4c27c60971
