### ISSUE TITLE
Прошу добавить в поддержку датчик Tyua _TZ3002_fdxihpp7 

### ISSUE THREAD

**Issue by yser1** [u236/homed-service-zigbee#204]
Прошу добавить в поддержку датчик Tyua  _TZ3002_fdxihpp7 / TS0001 одноканальный выключатель

{
  "active": true,
  "cloud": false,
  "description": "_TZ3002_fdxihpp7/TS0001",
  "discovery": false,
  "endpoints": [
    {
      "deviceId": 256,
      "endpointId": 1,
      "inClusters": [
        0,
        3,
        4,
        5,
        6,
        10,
        57344,
        57345
      ],
      "outClusters": [
        25
      ],
      "profileId": 260
    }
  ],
  "firmware": "0122052017",
  "ieeeAddress": "a4:c1:38:df:96:38:1d:0e",
  "interviewFinished": true,
  "lastSeen": 1724655006,
  "linkQuality": 184,
  "logicalType": 1,
  "manufacturerCode": 4107,
  "manufacturerName": "_TZ3002_fdxihpp7",
  "modelName": "TS0001",
  "name": "Вытяжка Подвал",
  "neighbors": [
    {
      "linkQuality": 221,
      "networkAddress": 0
    },
    {
      "linkQuality": 141,
      "networkAddress": 19347
    },
    {
      "linkQuality": 179,
      "networkAddress": 31140
    }
  ],
  "networkAddress": 24878,
  "powerSource": 1,
  "supported": false
}

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/39552fed99886f5b18378610f7877056f2fd6649
