### ISSUE TITLE
Датчик  _TZ3000_mgusv51k

### ISSUE THREAD

**Issue by yser1** [u236/homed-service-zigbee#205]
Посмотри, пожалуйста, определение датчика _TZ3000_mgusv51k / TS0052, в интерфейса пишет что "поддерживается"  и определяется как 2-х канальный диммер, а в реальности он 1-й канальный диммер.
В файле tuya.json поиском по модели " _TZ3000_mgusv51k" ничего не нашел. 

{
  "active": true,
  "cloud": false,
  "description": "TUYA TS0052/TS1101 2-Channel Dimmer",
  "discovery": false,
  "endpoints": [
    {
      "deviceId": 256,
      "endpointId": 1,
      "inClusters": [
        3,
        4,
        5,
        6,
        57344,
        57345,
        8,
        0
      ],
      "outClusters": [
        25,
        10
      ],
      "profileId": 260
    },
    {
      "deviceId": 97,
      "endpointId": 242,
      "outClusters": [
        33
      ],
      "profileId": 41440
    }
  ],
  "ieeeAddress": "a4:c1:38:f7:2c:e7:8e:3e",
  "interviewFinished": true,
  "lastSeen": 1724654817,
  "linkQuality": 255,
  "logicalType": 1,
  "manufacturerCode": 4417,
  "manufacturerName": "_TZ3000_mgusv51k",
  "modelName": "TS0052",
  "name": "Вытяжка Чердак",
  "neighbors": [
    {
      "linkQuality": 206,
      "networkAddress": 0
    },
    {
      "linkQuality": 57,
      "networkAddress": 24878
    },
    {
      "linkQuality": 75,
      "networkAddress": 31140
    }
  ],
  "networkAddress": 19347,
  "powerSource": 1,
  "supported": true,
  "version": 68
}

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/39552fed99886f5b18378610f7877056f2fd6649
