### ISSUE TITLE
Прошу добавить Smart Sprinkler Timer water metering _TZE204_uab532m0

### ISSUE THREAD

**Issue by gDIeMONd** [u236/homed-service-zigbee#209]
Приветствую!
Прошу добавить Smart Sprinkler Timer water metering _TZE204_uab532m0

https://github.com/Koenkk/zigbee2mqtt/issues/22813

**Comment by u236** [comment]
для добавления поддержки мне нужно устройство на руках, пока закрываю ишью, открою повторно, если появится устройство
