### ISSUE TITLE
Konke 2AJZ4KPBS - таймаут по умолчанию

### ISSUE THREAD

**Issue by u236** [u236/homed-service-zigbee#21]
сделать таймаут по умолчанию равным 2 минутам и добавить пометку на вики о том, что этот датчик - тупой

**Comment by Omirax** [comment]
Датчик не тупой, а позиционируется как аларм датчик скрытой установки. Он поэтому не мигает, когда срабатывает. Но отсутствие функции повторной отправки обнаружения движения или прекращения движения - ограничивает его область применения в системе УД

**Comment by u236** [comment]
> Датчик не тупой, а позиционируется как аларм датчик скрытой установки. Он поэтому не мигает, когда срабатывает. Но отсутствие функции повторной отправки обнаружения движения или прекращения движения - ограничивает его область применения в системе УД

Хорошо, тогда я попрошу тебя написать текст предупреждения для вики, потому что я не очень понимаю как это корректно донести :)

**Comment by u236** [comment]
поменял таймаут по умолчанию в https://github.com/u236/homed-service-zigbee/commit/f681d64bc90ee94ba283bb67f49cbe6e5f17e7c9
