### ISSUE TITLE
Please add s10 0/1-10v dimmer

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-zigbee#214]
![image](https://github.com/user-attachments/assets/8d5fdf9a-76ce-4898-a66a-742c78192696)

<img width="818" alt="image" src="https://github.com/user-attachments/assets/c6448d82-1e79-41dc-add2-95b16babdc9b">

2024.10.15 19:14:57.499 (inf) zigbee:     Permit join enabled successfully
2024.10.15 19:17:53.330 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" joined network with address "0xaceb"
2024.10.15 19:17:53.330 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" interview started...
2024.10.15 19:17:53.870 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" node descriptor received, manufacturer code is "0x100b" and logical type is "router"
2024.10.15 19:17:53.988 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" active endpoints received: "0x01"
2024.10.15 19:17:54.148 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" endpoint "0x01" simple descriptor received
2024.10.15 19:17:54.326 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" manufacturer name is "eWeLight" and model name is "ZB-DL01"
2024.10.15 19:17:54.334 (wrn) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" manufacturer name "eWeLight" and model name "ZB-DL01" not found in library
2024.10.15 19:17:54.334 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" endpoint "0x01" properties recognized: status, level
2024.10.15 19:17:54.334 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" endpoint "0x01" actions recognized: status, level
2024.10.15 19:17:54.334 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" endpoint "0x01" exposes recognized: light
2024.10.15 19:17:54.334 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" firmware is "2.0.1"
2024.10.15 19:17:54.334 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" identified as "eWeLight/ZB-DL01"
2024.10.15 19:17:54.490 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" endpoint "0x01" cluster "0x0006" binding to coordinator finished successfully
2024.10.15 19:17:54.634 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" endpoint "0x01" cluster "0x0008" binding to coordinator finished successfully
2024.10.15 19:17:54.808 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" endpoint "0x01" status reporting configuration request finished successfully
2024.10.15 19:17:54.847 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" endpoint "0x01" level reporting configuration request finished successfully
2024.10.15 19:17:54.847 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" interview finished successfully
2024.10.15 19:18:53.898 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" status action request finished successfully
2024.10.15 19:18:58.032 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" status action request finished successfully
2024.10.15 19:19:05.444 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" level action request finished successfully
2024.10.15 19:19:08.886 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" status action request finished successfully
2024.10.15 19:19:10.829 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" status action request finished successfully
2024.10.15 19:19:44.102 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" status action request finished successfully
2024.10.15 19:19:45.204 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" status action request finished successfully
2024.10.15 19:25:33.647 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" level action request finished successfully
2024.10.15 19:25:36.469 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" level action request finished successfully
2024.10.15 19:25:38.746 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" level action request finished successfully
2024.10.15 19:25:42.821 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" status action request finished successfully
2024.10.15 19:25:46.815 (inf) zigbee:     Device "a4:c1:38:43:d2:3a:8f:64" status action request finished successfully

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/a295d0aad338a0b5253119af222022688d31f996
