### ISSUE TITLE
Please add VALLHORN wireless motion sensor

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-zigbee#216]
![image](https://github.com/user-attachments/assets/c71193fe-49f2-4bc5-9240-862f45c5fbb3)
<img width="534" alt="image" src="https://github.com/user-attachments/assets/712ba0b1-434b-43ac-bf2b-f5ecc642efa6">

https://www.zigbee2mqtt.io/devices/E2134.html

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/42e03979a74e84e9919c96c523a5899939727ad0
