### ISSUE TITLE
Please add Gledopto GL-LB-001P

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-zigbee#217]
![image](https://github.com/user-attachments/assets/374c1515-d154-4d66-ae8d-93ec3cba8b0c)
<img width="859" alt="image" src="https://github.com/user-attachments/assets/757e6568-68e4-4014-b702-fa26696cd101">

https://www.zigbee2mqtt.io/devices/GL-LB-001P.html

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/42e03979a74e84e9919c96c523a5899939727ad0
