### ISSUE TITLE
Прошу добавить Tuya TS0601_thermostat

### ISSUE THREAD

**Issue by worm1982** [u236/homed-service-zigbee#218]
![изображение](https://github.com/user-attachments/assets/f848d35b-4cf2-4f93-9625-57cb74326088)
**Устройство**: https://www.zigbee2mqtt.io/devices/TS0601_thermostat.html#tuya-ts0601-thermostat

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/7468559703812a566e4cfd5be8cef215caef2972
