### ISSUE TITLE
второй датчик температуры TUYA TH03Z-z с прошивкой от pvvx

### ISSUE THREAD

**Issue by HomeNV** [u236/homed-service-zigbee#221]
датчик вот такой https://pvvx.github.io/TH03Z/

датчик тоже определяется нормально, нет поддержки и нет 3х настроек две калибровки и интервал
датчик прошит что бы была возможность настройки интервала и что бы показывал температуру ниже -20
https://github.com/Koenkk/zigbee-herdsman-converters/blob/5d0ca39277af13557d9fc7211162504dd2f461a2/src/devices/zigbeetlc.ts#L183

![2024-10-30_113002](https://github.com/user-attachments/assets/50a01bcc-8157-4324-acfa-5c1cf14703a6)

{
  "active": true,
  "cloud": false,
  "description": "Tuya/TH03Z-z",
  "discovery": false,
  "endpoints": [
    {
      "deviceId": 770,
      "endpointId": 1,
      "inClusters": [
        0,
        1,
        3,
        32,
        516,
        1026,
        1029
      ],
      "outClusters": [
        25
      ],
      "profileId": 260
    }
  ],
  "firmware": "3001-0123",
  "ieeeAddress": "a4:c1:38:b9:9a:dd:33:7f",
  "interviewFinished": true,
  "lastSeen": 1730276865,
  "linkQuality": 47,
  "logicalType": 2,
  "manufacturerCode": 4417,
  "manufacturerName": "Tuya",
  "modelName": "TH03Z-z",
  "name": "kitchen_ikeafridge_sth",
  "networkAddress": 38359,
  "ota": {
    "currentVersion": 19083265,
    "imageType": 534,
    "manufacturerCode": 4417,
    "running": false
  },
  "powerSource": 3,
  "supported": false
}

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/7271298e3658c793a1bb03848658f21fb9fa1249
