### ISSUE TITLE
прошу добавить в поддержку изделия мохнатой компании pushOk

### ISSUE THREAD

**Issue by HomeNV** [u236/homed-service-zigbee#222]
здесь весь список устройств https://github.com/Koenkk/zigbee-herdsman-converters/blob/3e3453fdd8c0def64232fed4973b58537a6f531c/src/devices/pushok.ts#L95

https://www.zigbee2mqtt.io/devices/POK005.html 
уличный датчик температуры
![2024-10-30_145323](https://github.com/user-attachments/assets/82ac648e-012f-4c45-a0e7-54e203b2bd4b)

{
  "active": true,
  "cloud": false,
  "description": "PushOk Hardware/POK005",
  "discovery": false,
  "endpoints": [
    {
      "deviceId": 770,
      "endpointId": 1,
      "inClusters": [
        0,
        3,
        1026,
        1029,
        1
      ],
      "outClusters": [
        0,
        25
      ],
      "profileId": 260
    }
  ],
  "ieeeAddress": "00:12:4b:00:2f:c3:44:55",
  "interviewFinished": true,
  "lastSeen": 1730289202,
  "linkQuality": 116,
  "logicalType": 2,
  "manufacturerCode": 0,
  "manufacturerName": "PushOk Hardware",
  "modelName": "POK005",
  "name": "outdoor_south_pushok_sth",
  "networkAddress": 39649,
  "ota": {
    "currentVersion": 8,
    "imageType": 7657,
    "manufacturerCode": 22136,
    "running": false
  },
  "powerSource": 3,
  "supported": false,
  "version": 8
}

https://www.zigbee2mqtt.io/devices/POK002_POK007.html
датчик влажности почвы
![2024-10-30_145249](https://github.com/user-attachments/assets/d2ddca1e-95b8-482f-9477-11a1edeab02e)

{
  "active": true,
  "cloud": false,
  "description": "PushOk Hardware/POK007",
  "discovery": false,
  "endpoints": [
    {
      "deviceId": 770,
      "endpointId": 1,
      "inClusters": [
        0,
        3,
        1026,
        1029,
        1
      ],
      "outClusters": [
        0,
        25
      ],
      "profileId": 260
    }
  ],
  "ieeeAddress": "00:12:4b:00:27:2c:d8:34",
  "interviewFinished": true,
  "lastSeen": 1730289026,
  "linkQuality": 58,
  "logicalType": 2,
  "manufacturerCode": 0,
  "manufacturerName": "PushOk Hardware",
  "modelName": "POK007",
  "name": "kitchen_dh_mandarin_pushok",
  "networkAddress": 2756,
  "powerSource": 3,
  "supported": false,
  "version": 7
}

https://www.zigbee2mqtt.io/devices/POK009.html
монитор напряжения 

![2024-10-30_145216](https://github.com/user-attachments/assets/61e5dc9f-de40-41de-afb9-78ce26398ab2)

{
  "active": true,
  "cloud": false,
  "description": "PushOk Hardware/POK009",
  "discovery": false,
  "endpoints": [
    {
      "deviceId": 12,
      "endpointId": 1,
      "inClusters": [
        0,
        3,
        1,
        19,
        12,
        20,
        15
      ],
      "outClusters": [
        0
      ],
      "profileId": 260
    },
    {
      "endpointId": 14,
      "outClusters": [
        25
      ],
      "profileId": 260
    }
  ],
  "ieeeAddress": "00:12:4b:00:2f:b4:b2:44",
  "interviewFinished": true,
  "lastSeen": 1730289298,
  "linkQuality": 174,
  "logicalType": 2,
  "manufacturerCode": 0,
  "manufacturerName": "PushOk Hardware",
  "modelName": "POK009",
  "name": "office_work_dc",
  "networkAddress": 8887,
  "ota": {
    "currentVersion": 5,
    "imageType": 7657,
    "manufacturerCode": 22136,
    "running": false
  },
  "powerSource": 3,
  "supported": false,
  "version": 5
}

https://www.zigbee2mqtt.io/devices/POK008.html
реле термостат

![2024-07-17_125032](https://github.com/user-attachments/assets/46362719-83ea-4772-ae49-d12929e962ab)
![2024-07-17_161128](https://github.com/user-attachments/assets/bb975ce7-2ba7-4757-8643-23e644f7e663)
![photo_2024-07-16_13-51-41](https://github.com/user-attachments/assets/57093396-3075-45d0-a4f3-b1fdafa8535c)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/93d343e39364ed92a18d9400d52986c42094997b
