### ISSUE TITLE
SONOFF/TRVZB

### ISSUE THREAD

**Issue by gDIeMONd** [u236/homed-service-zigbee#224]
Приветствую!
Прошу добавить SONOFF/TRVZB, она прошла автодискавери, но не хватает режима auto и может получится включить защиту от детей

{
  "active": true,
  "cloud": false,
  "description": "SONOFF/TRVZB",
  "discovery": false,
  "endpoints": [
    {
      "deviceId": 769,
      "endpointId": 1,
      "inClusters": [
        0,
        1,
        3,
        6,
        32,
        513,
        64599,
        64529
      ],
      "outClusters": [
        10,
        25
      ],
      "profileId": 260
    }
  ],
  "firmware": "1.1.1",
  "ieeeAddress": "88:1a:14:ff:fe:ec:bd:32",
  "interviewFinished": true,
  "lastSeen": 1730616309,
  "linkQuality": 52,
  "logicalType": 2,
  "manufacturerCode": 4742,
  "manufacturerName": "SONOFF",
  "modelName": "TRVZB",
  "name": "Термоголовка подвал лестница",
  "networkAddress": 12169,
  "ota": {
    "currentVersion": 4353,
    "imageType": 8199,
    "manufacturerCode": 4742,
    "running": false
  },
  "powerSource": 3,
  "supported": false
}

 
![image](https://github.com/user-attachments/assets/2ee78f66-605e-468f-8d4b-fc20fdc7b3a1)

https://www.zigbee2mqtt.io/devices/TRVZB.html

**Comment by u236** [comment]
для добавления поддержки нужно устройство на руках, пока закрываю ишью
