### ISSUE TITLE
SONOFF/SWV 

### ISSUE THREAD

**Issue by gDIeMONd** [u236/homed-service-zigbee#225]
Приветствую!
Прошу добавить SONOFF/SWV
{
  "active": true,
  "cloud": false,
  "description": "SONOFF/SWV",
  "discovery": false,
  "endpoints": [
    {
      "deviceId": 2,
      "endpointId": 1,
      "inClusters": [
        0,
        1,
        3,
        6,
        32,
        1028,
        2821,
        64599,
        64529
      ],
      "outClusters": [
        10,
        25
      ],
      "profileId": 260
    }
  ],
  "firmware": "1.0.4",
  "ieeeAddress": "84:27:12:ff:fe:17:aa:ed",
  "interviewFinished": true,
  "lastSeen": 1730625829,
  "linkQuality": 255,
  "logicalType": 2,
  "manufacturerCode": 4742,
  "manufacturerName": "SONOFF",
  "modelName": "SWV",
  "networkAddress": 10020,
  "powerSource": 3,
  "supported": false,
  "version": 16,
  "name": "84:27:12:ff:fe:17:aa:ed"
}

https://www.zigbee2mqtt.io/devices/SWV.html

**Comment by u236** [comment]
для добавления поддержки нужно устройство на руках, пока закрываю ишью
