### ISSUE TITLE
VALLHORN wireless motion sensor stopped working.

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-zigbee#226]
<img width="394" alt="image" src="https://github.com/user-attachments/assets/401e2161-1d1d-4a7d-8896-33fa72c24ae4">

**Было:**

2024.10.26 17:03:00.651 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" joined network with address "0xd02e"
2024.10.26 17:03:00.652 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" interview started...
2024.10.26 17:03:00.789 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" node descriptor received, manufacturer code is "0x117c" and logical type is "end device"
2024.10.26 17:03:01.067 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" active endpoints received: "0x01, 0x02, 0x03"
2024.10.26 17:03:01.360 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x01" simple descriptor received
2024.10.26 17:03:01.673 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x02" simple descriptor received
2024.10.26 17:03:01.955 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x03" simple descriptor received
2024.10.26 17:03:02.666 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" manufacturer name is "IKEA of Sweden" and model name is "VALLHORN Wireless Motion Sensor"
2024.10.26 17:03:02.673 (wrn) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" manufacturer name "IKEA of Sweden" and model name "VALLHORN Wireless Motion Sensor" not found in library
2024.10.26 17:03:02.673 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x01" properties recognized: battery
2024.10.26 17:03:02.674 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x01" exposes recognized: battery
2024.10.26 17:03:02.674 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x02" properties recognized: occupancy
2024.10.26 17:03:02.674 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x02" exposes recognized: occupancy
2024.10.26 17:03:02.674 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x03" properties recognized: illuminance
2024.10.26 17:03:02.674 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x03" exposes recognized: illuminance
2024.10.26 17:03:02.674 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" firmware is "1.0.64"
2024.10.26 17:03:02.674 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" identified as "IKEA of Sweden/VALLHORN Wireless Motion Sensor"
2024.10.26 17:03:04.657 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x01" cluster "0x0001" binding to coordinator finished successfully
2024.10.26 17:03:07.643 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x02" cluster "0x0406" binding to coordinator finished successfully
2024.10.26 17:03:09.649 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x03" cluster "0x0400" binding to coordinator finished successfully
2024.10.26 17:03:12.635 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x01" battery reporting configuration request finished successfully
2024.10.26 17:03:14.628 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x02" occupancy reporting configuration request finished successfully
2024.10.26 17:03:20.618 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" endpoint "0x03" illuminance reporting configuration request finished successfully
2024.10.26 17:03:20.618 (inf) zigbee:     Device "f8:44:77:ff:fe:84:03:1c" interview finished successfully

**Стало:**

2024.11.04 07:35:55.130 (inf) zigbee:     Device "VALLHORN" rejoined network with address "0xb9e6"
2024.11.04 07:35:55.130 (inf) zigbee:     Device "VALLHORN" network address updated
2024.11.04 07:35:55.130 (inf) zigbee:     Device "VALLHORN" interview started...
2024.11.04 07:35:56.260 (inf) zigbee:     Device "VALLHORN" node descriptor received, manufacturer code is "0x117c" and logical type is "end device"
2024.11.04 07:35:57.195 (inf) zigbee:     Device "VALLHORN" active endpoints received: "0x01, 0x02, 0x03"
2024.11.04 07:35:58.184 (inf) zigbee:     Device "VALLHORN" endpoint "0x01" simple descriptor received
2024.11.04 07:35:59.197 (inf) zigbee:     Device "VALLHORN" endpoint "0x02" simple descriptor received
2024.11.04 07:36:00.095 (inf) zigbee:     Device "HEATING" status action request finished successfully
2024.11.04 07:36:00.189 (inf) zigbee:     Device "VALLHORN" endpoint "0x03" simple descriptor received
2024.11.04 07:36:00.189 (inf) zigbee:     Device "informer-main" status action request finished successfully
2024.11.04 07:36:01.198 (inf) zigbee:     Device "VALLHORN" manufacturer name is "IKEA of Sweden" and model name is "VALLHORN Wireless Motion Sensor"
2024.11.04 07:36:01.202 (inf) zigbee:     Device "VALLHORN" firmware is "1.0.64"
2024.11.04 07:36:01.202 (inf) zigbee:     Device "VALLHORN" identified as "VALLHORN Motion Sensor E2134"
2024.11.04 07:36:02.194 (inf) zigbee:     Device "VALLHORN" endpoint "0x01" cluster "0x0001" binding to coordinator finished successfully
2024.11.04 07:36:03.166 (inf) zigbee:     Device "VALLHORN" endpoint "0x01" cluster "0x0406" binding to coordinator finished successfully
2024.11.04 07:36:04.163 (inf) zigbee:     Device "VALLHORN" endpoint "0x01" cluster "0x0400" binding to coordinator finished successfully
2024.11.04 07:36:04.196 (inf) zigbee:     Device "VALLHORN" endpoint "0x01" battery reporting configuration request finished successfully
2024.11.04 07:36:04.229 (inf) zigbee:     Device "VALLHORN" endpoint "0x01" occupancy reporting configuration request finished successfully
2024.11.04 07:36:04.262 (inf) zigbee:     Device "VALLHORN" endpoint "0x01" illuminance reporting configuration request finished successfully
2024.11.04 07:36:04.262 (inf) zigbee:     Device "VALLHORN" interview finished successfully
2024.11.04 07:36:04.844 (inf) zigbee:     Device "VALLHORN" battery status request finished successfully
2024.11.04 07:36:05.370 (wrn) zigbee:     Device "VALLHORN" endpoint "0x01" cluster "0x0406" reporting configuration error, status code: "0x86"
2024.11.04 07:36:05.370 (wrn) zigbee:     Device "VALLHORN" endpoint "0x01" cluster "0x0400" reporting configuration error, status code: "0x86"

**Comment by u236** [comment]
Потому что вместо скринов и ссылок на з2м нужно сразу кидать логи интервью и device info.
Проверяй: https://github.com/u236/homed-service-zigbee/commit/4ff0b3498cf637a6a488924eb94a39a74d8a566f.
