### ISSUE TITLE
Просьба добавить _TZ3000_egvb1p2g/TS004F

### ISSUE THREAD

**Issue by worm1982** [u236/homed-service-zigbee#227]
Здравствуйте, просьба добавить кнопку _TZ3000_egvb1p2g/TS004F

{
  "active": true,
  "cloud": true,
  "description": "_TZ3000_egvb1p2g/TS004F",
  "discovery": true,
  "endpoints": [
    {
      "endpointId": 1,
      "inClusters": [
        0,
        1,
        3,
        4,
        6,
        4096,
        57345
      ],
      "outClusters": [
        25,
        10,
        3,
        4,
        6,
        8,
        4096
      ],
      "profileId": 260
    }
  ],
  "firmware": "0122052017",
  "ieeeAddress": "a4:c1:38:84:22:cc:d6:41",
  "interviewFinished": true,
  "lastSeen": 1731097158,
  "linkQuality": 152,
  "logicalType": 2,
  "manufacturerCode": 4742,
  "manufacturerName": "_TZ3000_egvb1p2g",
  "modelName": "TS004F",
  "networkAddress": 24069,
  "powerSource": 3,
  "supported": false,
  "version": 144,
  "name": "a4:c1:38:84:22:cc:d6:41"
}

https://www.zigbee2mqtt.io/devices/ZG-101ZL.html

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/ed777f0f06f5f02aea12b49ba7e006cfcc67da24
