### ISSUE TITLE
Просьба добавить TZ3000_wpueorev Smart Valve Controller 

### ISSUE THREAD

**Issue by Olegarh74** [u236/homed-service-zigbee#229]
{
  "active": true,
  "cloud": true,
  "description": "_TZ3000_wpueorev/TS0001",
  "discovery": true,
  "endpoints": [
    {
      "deviceId": 256,
      "endpointId": 1,
      "inClusters": [
        3,
        4,
        5,
        6,
        57344,
        57345,
        0
      ],
      "outClusters": [
        25,
        10
      ],
      "profileId": 260
    },
    {
      "deviceId": 97,
      "endpointId": 242,
      "outClusters": [
        33
      ],
      "profileId": 41440
    }
  ],
  "ieeeAddress": "a4:c1:38:1b:e9:19:a8:9f",
  "interviewFinished": true,
  "lastSeen": 1734378061,
  "linkQuality": 116,
  "logicalType": 1,
  "manufacturerCode": 4417,
  "manufacturerName": "_TZ3000_wpueorev",
  "modelName": "TS0001",
  "name": "Холодная вода реле",
  "neighbors": [
    {
      "linkQuality": 173,
      "networkAddress": 0
    },
    {
      "linkQuality": 0,
      "networkAddress": 6906
    }
  ],
  "networkAddress": 45663,
  "powerSource": 1,
  "supported": false,
  "version": 83
}

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/be5582cf5483701884fd830f3f3fe9614f63b645
