### ISSUE TITLE
Просьба добавить Aqara Smart natural gas detector JT-BZ-03AQ/A

### ISSUE THREAD

**Issue by fort999** [u236/homed-service-zigbee#230]
https://www.zigbee2mqtt.io/devices/JT-BZ-01AQ_A.html

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/d86560bbad138b290afe6c040f07776f88dc9a2f

**Comment by fort999** [comment]
Спасибо. Но не отдает action совсем. Проверил выключатель в z2m - там норм.
