### ISSUE TITLE
Air Sensor: LifeControl (MCLH-08) fix temperature parameter name

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#26]
Payload '{"battery":92,"co2":1399,"humidity":39.8,"linkQuality":160,"**tempertature**":24.38,"voc":152}'

Mistake in temperature parameter name - tempertature

**Comment by u236** [comment]
fixed in https://github.com/u236/homed-service-zigbee/commit/3c9c33b17445b5880b974fb0208120933a1f8816
