### ISSUE TITLE
Add support Aqara human body movement and illuminance sensor (RTCGQ11LM)

### ISSUE THREAD

**Issue by avaksru** [u236/homed-service-zigbee#27]
Датчик движения и освещения Aqara Motion Sensor  (RTCGQ11LM)
https://aqara.ru/product/aqara-motion-sensor/

Model	RTCGQ11LM
Vendor	Xiaomi
Exposes	battery, occupancy, device_temperature, voltage, illuminance_lux, illuminance, power_outage_count, linkquality

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/0f11269795dbfb761cbd507a261b9556bf7dc5cf

**Comment by u236** [comment]
освещенность вычисляется некорректно

**Comment by u236** [comment]
исправлено в https://github.com/u236/homed-service-zigbee/commit/ed8228557f68af23ac3f190bfb30ab6455c7b71f
