### ISSUE TITLE
Add support Aqara temperature, humidity and pressure sensor (	WSDCGQ11LM)

### ISSUE THREAD

**Issue by avaksru** [u236/homed-service-zigbee#28]
Датчик температуры и влажности Aqara Temperature and Humidity Sensor  (	WSDCGQ11LM)
Model	WSDCGQ11LM
Vendor	Xiaomi
Description	Aqara temperature, humidity and pressure sensor
Exposes	battery, temperature, humidity, pressure, voltage, linkquality

**Comment by u236** [comment]
Включи пожалуйста отладочные сообщения в файле конфигурации, и пришли лог с сообщениями от датчика:
```ini
[debug]
adapter=false
zigbee=true
```

**Comment by avaksru** [comment]
Готово
https://live-control.com/homed/homed.log

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/0f11269795dbfb761cbd507a261b9556bf7dc5cf
давление пулбликуется в кПа
