### ISSUE TITLE
Добавить счетчик электроэнергии XOCA DAC2161С Tuya (TS0601)

### ISSUE THREAD

**Issue by Sborkahome** [u236/homed-service-zigbee#29]
[count.txt](https://github.com/u236/homed-service-zigbee/files/10280638/count.txt)

**Comment by Sborkahome** [comment]
[count_1.txt](https://github.com/u236/homed-service-zigbee/files/10296343/count_1.txt)

**Comment by u236** [comment]
Реализовано в https://githbub.com/u236/homed-service-zigbee/commit/8aa1592904cc9aafd589e039b4d83168014c58c3

**Comment by u236** [comment]
Реализовано в https://github.com/u236/homed-service-zigbee/commit/8aa1592904cc9aafd589e039b4d83168014c58c3
