### ISSUE TITLE
Добавить топик статуса

### ISSUE THREAD

**Issue by kerenskiy** [u236/homed-service-zigbee#3]
Добавить топик статуса (service/status=online) для отслеживания работы сервиса.

**Comment by u236** [comment]
Это реализовано в версии <code>3.0.37</code>, данные публикуются в топик <code>homed/service/zigbee</code>.
При старте приложения:
```json
{
  "started":"2022-10-19T10:10:43.988","uptime":0}
```

**Comment by u236** [comment]
В следующем релизе добавлю MQTT LWT фичи.

**Comment by u236** [comment]
Реализовал MQTT LWT в https://github.com/u236/homed-service-common/commit/e27bd210bdd9bf7ef276417e7d53c0d90cc4a55b, сообщение сокращено.

При старте приложения:
```json
{
  "status": "online"
}
```

При отсановке/падении приложения или потере соединения с брокером:
```json
{
  "status": "offline"
}
```
