### ISSUE TITLE
Добавить ptvo-switch

### ISSUE THREAD

**Issue by Sborkahome** [u236/homed-service-zigbee#35]
[ptvo.txt](https://github.com/u236/homed-service-zigbee/files/10354995/ptvo.txt)
Это бывшее WiFi реле, переделанное под зигби.
[LC-Relay-ESP01-4R-5V.pdf](https://github.com/u236/homed-service-zigbee/files/10355037/LC-Relay-ESP01-4R-5V.pdf)

**Comment by Sborkahome** [comment]
[Топики_mqtt_для_включения_реле.txt](https://github.com/u236/homed-service-zigbee/files/10355013/_mqtt_._._.txt)
Это пример топиков для данного реле, которое подключалось к Z2M.

**Comment by u236** [comment]
Устройства с прошивкой PTVO уникальны, нет смысла добавлять их в библиотеку. В обозримом будущем, вероятно, появится возможность автоматического определения всех функций устройств с прошивкой PTVO, тогда можно будет вернуться к этому реле.

**Comment by Sborkahome** [comment]
https://ptvo.info/zigbee-configurable-firmware-features/uart/
а может эта ссылка поможет? Работа с UARTом

**Comment by u236** [comment]
> https://ptvo.info/zigbee-configurable-firmware-features/uart/
> 
> а может эта ссылка поможет? Работа с UARTом

Вопрос не в том, чтобы понять как это работает, а в том, что это уникальное устройство, существущее, скорее всего, в единственном экземпляре. Если я буду добавлять каждую подробную свистелку на PTVO в общую библиотеку, скоро библиотека будет на 99% состоять из этих свистелок. Поэтому надо подождать, пока в PTVO появится функционал, который позволит работать с такими устройствами без добавления их в библиотеку.
