### ISSUE TITLE
добавить поддержку лампочки "Trust International B.V. ZLL-DimmableLigh"

### ISSUE THREAD

**Issue by Sborkahome** [u236/homed-service-zigbee#38]
Wed Jan 11 21:14:54 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:14:54.020 (inf) zigbee:    Permit join enabled successfully
Wed Jan 11 21:15:13 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:13.438 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" joined network with address "0x0cb6"
Wed Jan 11 21:15:13 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:13.442 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" interview started...
Wed Jan 11 21:15:13 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:13.573 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" node descriptor received, manufacturer code is "0x1037" and logical type is "router"
Wed Jan 11 21:15:13 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:13.690 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" active endpoints received: "0x01, 0x02"
Wed Jan 11 21:15:13 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:13.870 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" endpoint "0x01" simple descriptor received
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.053 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" endpoint "0x02" simple descriptor received
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.183 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" endpoint "0x01" cluster "0x0000" attribute "0x0001" report received with type "0x20" and data "01" and transaction id 70
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.187 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" endpoint "0x01" cluster "0x0000" attribute "0x0004" report received with type "0x42" and data "54:72:75:73:74:20:49:6e:74:65:72:6e:61:74:69:6f:6e:61:6c:20:42:2e:56:2e:00" and transaction id 70
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.191 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" endpoint "0x01" cluster "0x0000" attribute "0x0005" report received with type "0x42" and data "5a:4c:4c:2d:44:69:6d:6d:61:62:6c:65:4c:69:67:68" and transaction id 70
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.195 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" endpoint "0x01" cluster "0x0000" attribute "0x0007" report received with type "0x30" and data "01" and transaction id 70
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.198 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" manufacturer name is "Trust International B.V." and model name is "ZLL-DimmableLigh"
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.231 (wrn) zigbee:    Device "00:15:8d:00:01:c0:1d:58" manufacturer name "Trust International B.V." and model name "ZLL-DimmableLigh" properties not found in library
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.234 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" endpoint "0x01" properties recognized: "status, level"
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.238 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" endpoint "0x01" actions recognized: "status, level"
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.241 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" endpoint "0x01" discoveries: "light"
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.244 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" identified as "Trust International B.V./ZLL-DimmableLigh"
Wed Jan 11 21:15:14 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:14.247 (inf) zigbee:    Device "00:15:8d:00:01:c0:1d:58" interview finished successfully
Wed Jan 11 21:15:25 2023 daemon.info homed-zigbee[3593]: 2023.01.11 21:15:25.829 (inf) zigbee:    Permit join disabled successfully

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/1fb7f6b8a46aaa03507fc437fcf5c1b34db5cd02
