### ISSUE TITLE
добавить поддержку "lumi.sensor_magnet.aq2"

### ISSUE THREAD

**Issue by Sborkahome** [u236/homed-service-zigbee#39]
Thu Jan 12 21:25:45 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:45.541 (inf) zigbee:    Permit join enabled successfully
Thu Jan 12 21:25:58 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:58.223 (inf) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" joined network with address "0xc63c"
Thu Jan 12 21:25:58 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:58.227 (inf) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" interview started...
Thu Jan 12 21:25:59 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:59.305 (inf) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" node descriptor received, manufacturer code is "0x1037" and logical type is "end device"
Thu Jan 12 21:25:59 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:59.586 (inf) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" active endpoints received: "0x01"
Thu Jan 12 21:25:59 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:59.823 (inf) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" endpoint "0x01" simple descriptor received
Thu Jan 12 21:25:59 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:59.956 (inf) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" manufacturer name is "LUMI" and model name is "lumi.sensor_magnet.aq2"
Thu Jan 12 21:25:59 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:59.988 (wrn) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" manufacturer name "LUMI" and model name "lumi.sensor_magnet.aq2" properties not found in library
Thu Jan 12 21:25:59 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:59.992 (inf) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" endpoint "0x01" properties recognized: "action"
Thu Jan 12 21:25:59 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:25:59.996 (inf) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" identified as "LUMI/lumi.sensor_magnet.aq2"
Thu Jan 12 21:26:00 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:26:00.000 (inf) zigbee:    Device "00:15:8d:00:07:2b:8d:a9" interview finished successfully
Thu Jan 12 21:26:33 2023 daemon.info homed-zigbee[3801]: 2023.01.12 21:26:33.598 (inf) zigbee:    Permit join disabled successfully

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/1fb7f6b8a46aaa03507fc437fcf5c1b34db5cd02
