### ISSUE TITLE
Добавить отображение версии прошивки координатора

### ISSUE THREAD

**Issue by kerenskiy** [u236/homed-service-zigbee#4]
Добавить отображение текущей версии прошивки координатора для удобства обновления прошивки стика.

**Comment by u236** [comment]
Частично реализовано в https://github.com/u236/homed-service-zigbee/commit/2d8e5c6b2f1e315fc40b18035e728f7027f03c8d, так же добавлено новых поле  базы данных <code>type</code> для координатора. Для Z-Stack конкретный номер версии прошивки пока не определяется, не уверен что это вообще возможно.

**Comment by u236** [comment]
Добавил определение версии Z-Stack в https://github.com/u236/homed-service-zigbee/commit/3f1f31cfd3a511f4512117570c1bb7a3adbecbed.
