### ISSUE TITLE
Просьба добавить поддержку беспроводной кнопки Aqara D1 (WXKG07LM)

### ISSUE THREAD

**Issue by akseugene** [u236/homed-service-zigbee#43]
Логи джойна:
(inf) zigbee: Permit join enabled successfully
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" joined network with address "0xcb31"
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" interview started...
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" node descriptor received, manufacturer code is "0x1037" and logical type is "end device"
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" active endpoints received: "0x01, 0x02, 0x03"
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" endpoint "0x01" simple descriptor received
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" endpoint "0x02" simple descriptor received
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" endpoint "0x03" simple descriptor received
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" manufacturer name is "LUMI" and model name is "lumi.remote.b286acn02"
(wrn) zigbee: Device "00:15:8d:00:04:4e:74:da" manufacturer name "LUMI" and model name "lumi.remote.b286acn02" properties not found in library
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" identified as "LUMI/lumi.remote.b286acn02"
(inf) zigbee: Device "00:15:8d:00:04:4e:74:da" interview finished successfully

Свойства объекта:
00:15:8d:00:04:4e:74:da
{
    "description": "LUMI/lumi.remote.b286acn02",
    "endpoints": [
        {
            "deviceId": 24321,
            "endpointId": 1,
            "inClusters": [
                0,
                3,
                25,
                65535,
                18
            ],
            "outClusters": [
                0,
                4,
                3,
                5,
                25,
                65535,
                18
            ],
            "profileId": 260
        },
        {
            "deviceId": 24322,
            "endpointId": 2,
            "inClusters": [
                3,
                18
            ],
            "outClusters": [
                4,
                3,
                5,
                18
            ],
            "profileId": 260
        },
        {
            "deviceId": 24323,
            "endpointId": 3,
            "inClusters": [
                3,
                12
            ],
            "outClusters": [
                4,
                3,
                5,
                12
            ],
            "profileId": 260
        }
    ],
    "ieeeAddress": "00:15:8d:00:04:4e:74:da",
    "interviewFinished": true,
    "lastSeen": 1674468491,
    "linkQuality": 97,
    "logicalType": 2,
    "manufacturerCode": 4151,
    "manufacturerName": "LUMI",
    "modelName": "lumi.remote.b286acn02",
    "networkAddress": 52017,
    "powerSource": 3,
    "supported": false,
    "version": 9
}

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/b327dc20b5f58c9d8bba1feac78d3292f59c19f5
