### ISSUE TITLE
Поддержка датчика протечки Триколор\GS\HEIMAN

### ISSUE THREAD

**Issue by DGMiron** [u236/homed-service-zigbee#44]
https://www.zigbee2mqtt.io/devices/SWHM-I1.html

2023.02.13 13:39:51.427 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" interview started...
2023.02.13 13:39:52.423 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" node descriptor received, manufacturer code is "0x120b" and logical type is "end device"
2023.02.13 13:39:53.433 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" active endpoints received: "0x01"
2023.02.13 13:39:54.459 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" endpoint "0x01" simple descriptor received
2023.02.13 13:39:56.463 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" endpoint "0x01" IAS zone type: "0x002a"
2023.02.13 13:39:58.478 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" endpoint "0x01" IAS zone enrolled
2023.02.13 13:39:58.481 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" manufacturer name is "GS" and model name is "SWHM-I1"
2023.02.13 13:39:58.519 (wrn) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" manufacturer name "GS" and model name "SWHM-I1" properties not found in library
2023.02.13 13:39:58.522 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" endpoint "0x01" properties recognized: "battery, alarm"
2023.02.13 13:39:58.526 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" endpoint "0x01" discoveries: "battery, alarm"
2023.02.13 13:39:58.529 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" identified as "GS/SWHM-I1"
2023.02.13 13:39:58.533 (inf) zigbee:    Device "00:0d:6f:00:13:14:e2:ad" interview finished successfully
2023.02.13 13:40:09.542 (inf) zigbee:    Permit join disabled successfully

![изображение](https://user-images.githubusercontent.com/88690230/218438410-02537498-201d-41b7-9218-18cca69b7c1b.png)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/5a14dc0f35be55b50df02ac02806705966b8b7c5
