### ISSUE TITLE
Поддержка розетки Xiaomi ZNCZ04LM

### ISSUE THREAD

**Issue by DGMiron** [u236/homed-service-zigbee#45]
https://www.zigbee2mqtt.io/devices/ZNCZ04LM.html#xiaomi-zncz04lm

2023.02.13 23:20:08.151 (inf) zigbee:    Permit join enabled successfully
2023.02.13 23:21:05.099 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" joined network with address "0xea2d"
2023.02.13 23:21:05.102 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" interview started...
2023.02.13 23:21:05.224 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" node descriptor received, manufacturer code is "0x115f" and logical type is "router"
2023.02.13 23:21:05.334 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" active endpoints received: "0x01, 0xf2"
2023.02.13 23:21:05.472 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" endpoint "0x01" simple descriptor received
2023.02.13 23:21:05.592 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" endpoint "0xf2" simple descriptor received
2023.02.13 23:21:05.722 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" manufacturer name is "LUMI" and model name is "lumi.plug.mmeu01"
2023.02.13 23:21:05.755 (wrn) zigbee:    Device "04:cf:8c:df:3c:75:98:76" manufacturer name "LUMI" and model name "lumi.plug.mmeu01" properties not found in library
2023.02.13 23:21:05.760 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" endpoint "0x01" properties recognized: "temperature, status, energy, voltage, current, power"
2023.02.13 23:21:05.763 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" endpoint "0x01" actions recognized: "status"
2023.02.13 23:21:05.767 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" endpoint "0x01" discoveries: "temperature, switch, energy, voltage, current, power"
2023.02.13 23:21:05.772 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" identified as "LUMI/lumi.plug.mmeu01"
2023.02.13 23:21:05.775 (inf) zigbee:    Device "04:cf:8c:df:3c:75:98:76" interview finished successfully
2023.02.13 23:21:06.462 (wrn) zigbee:    No property found for device "04:cf:8c:df:3c:75:98:76" endpoint "0x01" cluster "0xfcc0" attribute "0x00f7" report with type "0x41" and data "64:10:00:03:28:1e:98:39:00:00:00:00:95:39:32:2a:49:42:96:39:00:00:07:45:97:39:00:00:00:00:05:21:01:00:9a:20:10:08:21:16:01:07:27:00:00:00:00:00:00:00:00:09:21:00:03:0b:20:00:9b:10:00"
2023.02.13 23:21:08.038 (wrn) zigbee:    No property found for device "04:cf:8c:df:3c:75:98:76" endpoint "0x01" cluster "0xfcc0" attribute "0x00f7" report with type "0x41" and data "64:10:00:03:28:1b:98:39:00:00:00:00:95:39:32:2a:49:42:96:39:00:00:07:45:97:39:00:00:00:00:05:21:01:00:9a:20:00:08:21:16:01:07:27:00:00:00:00:00:00:00:00:09:21:00:03:0b:20:00:9b:10:00"
2023.02.13 23:21:10.231 (wrn) zigbee:    No property found for device "04:cf:8c:df:3c:75:98:76" endpoint "0x01" cluster "0xfcc0" attribute "0x0207" report with type "0x10" and data "00"

![изображение](https://user-images.githubusercontent.com/88690230/218567126-505fbe5a-f35b-4687-8b92-3f28f1d89d7c.png)

Вкл/выкл работает. Линк передает. Сенсоры не прилетают

**Comment by u236** [comment]
Добавил в https://github.com/u236/homed-service-zigbee/commit/8180420e195b4d65f488ed9551a9cf71f682e406
