### ISSUE TITLE
Поддержка Open Lumi Gateway (Alternate OpenWRT on DGNWG05LM and ZHWG11LM) с прошивкой зигби как роутер-лампа Philips

### ISSUE THREAD

**Issue by DGMiron** [u236/homed-service-zigbee#46]
https://www.zigbee2mqtt.io/devices/3115331PH.html

2023.02.13 23:47:17.653 (inf) zigbee:    Permit join enabled successfully
2023.02.13 23:47:31.434 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" joined network with address "0x35b2"
2023.02.13 23:47:31.438 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" interview started...
2023.02.13 23:47:31.549 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" node descriptor received, manufacturer code is "0x1037" and logical type is "router"
2023.02.13 23:47:31.668 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" active endpoints received: "0x01"
2023.02.13 23:47:31.825 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" endpoint "0x01" simple descriptor received
2023.02.13 23:47:32.061 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" endpoint "0x01" color capabilities: "0x001f"
2023.02.13 23:47:32.065 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" manufacturer name is "Openlumi" and model name is "HML004"
2023.02.13 23:47:32.101 (wrn) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" manufacturer name "Openlumi" and model name "HML004" properties not found in library
2023.02.13 23:47:32.108 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" endpoint "0x01" properties recognized: "status, level, color, colorTemperature"
2023.02.13 23:47:32.112 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" endpoint "0x01" actions recognized: "status, level, color, colorTemperature"
2023.02.13 23:47:32.115 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" endpoint "0x01" discoveries: "light"
2023.02.13 23:47:32.119 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" identified as "Openlumi/HML004"
2023.02.13 23:47:32.122 (inf) zigbee:    Device "00:15:8d:00:03:ce:ef:f9" interview finished successfully
2023.02.13 23:47:56.562 (inf) zigbee:    Permit join disabled successfully

![изображение](https://user-images.githubusercontent.com/88690230/218575613-455dd979-c17a-4ce0-bbfd-273e91d6b9ef.png)

**Comment by u236** [comment]
Добавил в https://github.com/u236/homed-service-zigbee/commit/8180420e195b4d65f488ed9551a9cf71f682e406
