### ISSUE TITLE
GS/STHM-I1H Датчик температуры

### ISSUE THREAD

**Issue by mrTURav** [u236/homed-service-zigbee#47]
Просьба добавить устройство в список поддерживаемых. 

Description | GS/STHM-I1H
-- | --
Logical type | end device
Power source |  
IEEE address | 00:0d:6f:00:13:36:1a:77
Network address | 0x0602
Manufacturer code | 0x120b
Manufacturer name | GS
Model name | STHM-I1H
Version | 25
I

{
    "description": "GS/STHM-I1H",
    "endpoints": [
        {
            "deviceId": 770,
            "endpointId": 1,
            "inClusters": [
                0,
                1,
                3,
                9,
                1026,
                1029,
                65528
            ],
            "outClusters": [
                3,
                25
            ],
            "profileId": 260
        }
    ],
    "ieeeAddress": "00:0d:6f:00:13:36:1a:77",
    "interviewFinished": true,
    "lastSeen": 1677163348,
    "linkQuality": 212,
    "logicalType": 2,
    "manufacturerCode": 4619,
    "manufacturerName": "GS",
    "modelName": "STHM-I1H",
    "name": "Температура улица",
    "networkAddress": 1538,
    "powerSource": 3,
    "supported": false,
    "version": 25
}

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/4e04763fa6973a16e93465ddacfa82b367ecfca9
