### ISSUE TITLE
TUYA TS0001/TS0011 Gas/Water Valve Motor

### ISSUE THREAD

**Issue by DGMiron** [u236/homed-service-zigbee#51]
Просьба добавить Manufacturer name "_TZ3000_5ucujjts" . А то без него пишет не поддерживается и Power on status не настраивается.
![image](https://github.com/u236/homed-service-zigbee/assets/88690230/d93ccf86-72fb-4bef-aa55-b6f59e4e40a3)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commits/master
