### ISSUE TITLE
eWeLink Switch ZR-02 с прошивкой PTVO

### ISSUE THREAD

**Issue by DGMiron** [u236/homed-service-zigbee#52]
Прошивка https://t.me/zigbeeptvo/13476
Судя по конвертору для з2м: рэле - свич, кнопка - экшн, есть температура чипа. Ещё, вроде, есть Power on status.
Автораспознаётся только свич. Своими силами удалось добавить температуру чипа (не знаю, - зачем она нужна, но всё ж..)
Не осилил экшн кнопки. 
Сделал таким образом:
```
{
  "ptvo.switch-zr02":
  [
   {
     "description":    "my_ptvo.switch",
      "modelNames":     ["ptvo.switch-zr02"],
      "properties":     ["status"],
      "actions":        ["status"],
      "exposes":        ["switch"],
      "endpointId":     2
   },
   {
     "modelNames":     ["ptvo.switch-zr02"],
      "properties":     ["ptvoTemperature"],
      "exposes":        ["temperature"],
      "endpointId":     3
   }
  ]
}
```
Прошу помощи, подсказки в добавлении кнопки.

**Comment by u236** [comment]
добавил новое свойство "ptvoButtonAction" в https://github.com/u236/homed-service-zigbee/commit/cdef67cc3fdc4a9127684bcf667e119c8f520e11, потестировать можно, взяв бинарник под нужную архитекутру здесь: http://sandbox.u236.org/homed-zigbee/ (нужно не забыть сделать бинарник исполняемым после замены файла)

**Comment by DGMiron** [comment]
Изменил либу, проверил - работает!!! Спасибо!
Содержание библиотеки: https://pastebin.com/ETrwVjtK
![Снимок экрана от 2023-05-24 19-02-36](https://github.com/u236/homed-service-zigbee/assets/88690230/c571da18-87b0-4b0a-b717-7a2a1800127d)
![Снимок экрана от 2023-05-24 19-02-51](https://github.com/u236/homed-service-zigbee/assets/88690230/92a1330b-9f0a-4a98-9afb-e7898c166eb0)
![Снимок экрана от 2023-05-24 19-03-04](https://github.com/u236/homed-service-zigbee/assets/88690230/45473200-d95b-4cef-9298-e4ce88c2c440)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/ecf6791c3c93f18467db081510141f63e80f8b96
