### ISSUE TITLE
Добавить unit_of_measurment для battery в homeassistant discovery

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#53]
Добавить unit_of_measurment для battery в homeassistant discovery

- Life Control Door and Window Sensor MCLH-04
- Life Control Air Quality Sensor MCLH-08

**Comment by u236** [comment]
Единица измерения для батареи высталяется независимо от устройства:

**Comment by u236** [comment]
Посмотрел код, увидел, почему у этих датчиков нет единицы измерения для батареи, поправил :)
https://github.com/u236/homed-service-zigbee/commit/41a50eff78e58573eef57ddd6a7190e496f54808
