### ISSUE TITLE
Просьба добавить поддержку устройства

### ISSUE THREAD

**Issue by DGMiron** [u236/homed-service-zigbee#55]
Просьба добавить поддержку устройства:
https://t.me/zigbeat/2061
https://aliexpress.ru/item/1005005453758738.html
![photo_2023-06-01_22-52-36](https://github.com/u236/homed-service-zigbee/assets/88690230/d05fb655-2763-41b4-b6b8-78465ccdda9e)
Лог интервью:
![Снимок экрана от 2023-05-31 18-19-51](https://github.com/u236/homed-service-zigbee/assets/88690230/3db0361c-3f2f-49c5-8131-afcf60968a91)
![Снимок экрана от 2023-05-31 18-21-26](https://github.com/u236/homed-service-zigbee/assets/88690230/7200bb25-1cda-4ba3-bc96-0992c859b8aa)
![Снимок экрана от 2023-05-31 18-21-43](https://github.com/u236/homed-service-zigbee/assets/88690230/0bc725a9-3d1e-4c1a-8bd8-df8eb504b116)

**Comment by u236** [comment]
нужно тестировать
https://github.com/u236/homed-service-zigbee/commit/46871cb6b90e8d0e845af7eb8bb40194ff28373e
