### ISSUE TITLE
Совместимость еденицы измерения освещения с Home Assistant

### ISSUE THREAD

**Issue by Deniom3** [u236/homed-service-zigbee#58]
При добавления датчика освещения в Home Assistant через Homed получаем предупреждение о несовместимых единицах измерения. 

Предупреждение из HA:
Entity sensor.bedroom_motion_illuminance (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'lux' which is not a valid unit for the device class ('illuminance') it is using; expected one of ['lx'];

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/7e87b76baca7fc810f35217ce39b5e7397cf9795
