### ISSUE TITLE
TUYA TS0601 Electricity Meter (Type A)

### ISSUE THREAD

**Issue by NE8XT** [u236/homed-service-zigbee#59]
| Service: 3.4.0 | 
После апдейта 5 июня на эту версию, перестали работать данные устройства.
![telegram-cloud-photo-size-4-5787285968720608424-y](https://github.com/u236/homed-service-zigbee/assets/77930301/40fe9ad1-1372-4286-a0cd-1b5154d3c743)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/2ea5dced4941a6c4d9a57dfbafa5ac26196186af
