### ISSUE TITLE
Add support Tuya smart socket TS011F ( _TZ3000_gjnozsaz )

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#6]
Smart Socket TS011F family  / Power Plug NAS-WR01B
https://aliexpress.ru/item/1005003658767835.html
Blue Version with Energy Monitor

2022.10.26 15:33:28.471 (inf) zigbee:    Device "a4:c1:38:50:33:d8:30:07" joined network with address "0xA024"
2022.10.26 15:33:28.545 (inf) zigbee:    Device "a4:c1:38:50:33:d8:30:07" is router
2022.10.26 15:33:28.548 (inf) zigbee:    Device "a4:c1:38:50:33:d8:30:07" node descriptor received, manufacturer code: "0x1141"
2022.10.26 15:33:28.620 (inf) zigbee:    Device "a4:c1:38:50:33:d8:30:07" active endpoints received: "0x01, 0xF2"
2022.10.26 15:33:28.696 (inf) zigbee:    Device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" simple descriptor received
2022.10.26 15:33:28.769 (inf) zigbee:    Device "a4:c1:38:50:33:d8:30:07" endpoint "0xF2" simple descriptor received
2022.10.26 15:33:28.851 (wrn) zigbee:    Device "a4:c1:38:50:33:d8:30:07" manufacturer name "_TZ3000_gjnozsaz" unrecognized
2022.10.26 15:33:28.854 (inf) zigbee:    Device "a4:c1:38:50:33:d8:30:07" manufacturer name is "_TZ3000_gjnozsaz" and model name is "TS011F"
2022.10.26 15:33:28.857 (inf) zigbee:    Device "a4:c1:38:50:33:d8:30:07" interview finished
2022.10.26 15:33:33.918 (wrn) zigbee:    Unrecognized attribute "0xD001" data type "0x48" received from device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE000" with payload: "02:00:06"
2022.10.26 15:33:33.997 (wrn) zigbee:    Unrecognized attribute "0xD002" data type "0x48" received from device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE000" with payload: "02:00:0a"
2022.10.26 15:33:34.090 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0x0006" attribute "0x0000" with data type "0x10" and data "01"
2022.10.26 15:33:34.096 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0x0006" attribute "0x4001" with data type "0x21" and data "00:00"
2022.10.26 15:33:34.100 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0x0006" attribute "0x4002" with data type "0x21" and data "00:00"
2022.10.26 15:33:34.103 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0x0006" attribute "0x8001" with data type "0x30" and data "01"
2022.10.26 15:33:34.106 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0x0006" attribute "0x8002" with data type "0x30" and data "02"
2022.10.26 15:33:34.110 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0x0006" attribute "0x5000" with data type "0x30" and data "01"
2022.10.26 15:33:34.114 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0x0006" attribute "0x8000" with data type "0x10" and data "00"
2022.10.26 15:33:34.401 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD010" with data type "0x30" and data "02"
2022.10.26 15:33:34.405 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD030" with data type "0x30" and data "00"
2022.10.26 15:33:34.408 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD000" with data type "0x20" and data "00"
2022.10.26 15:33:34.411 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD001" with data type "0x1B" and data "00:00:00:00"
2022.10.26 15:33:34.415 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD002" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.418 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD003" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.422 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD004" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.425 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD005" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.601 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD010" with data type "0x30" and data "02"
2022.10.26 15:33:34.604 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD030" with data type "0x30" and data "00"
2022.10.26 15:33:34.608 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD000" with data type "0x20" and data "00"
2022.10.26 15:33:34.611 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD001" with data type "0x1B" and data "00:00:00:00"
2022.10.26 15:33:34.614 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD002" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.618 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD003" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.621 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD004" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.625 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD005" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.808 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD010" with data type "0x30" and data "02"
2022.10.26 15:33:34.811 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD030" with data type "0x30" and data "00"
2022.10.26 15:33:34.815 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD000" with data type "0x20" and data "00"
2022.10.26 15:33:34.818 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD001" with data type "0x1B" and data "00:00:00:00"
2022.10.26 15:33:34.821 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD002" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.824 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD003" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.828 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD004" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:34.831 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD005" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:35.002 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD010" with data type "0x30" and data "02"
2022.10.26 15:33:35.006 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD030" with data type "0x30" and data "00"
2022.10.26 15:33:35.009 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD000" with data type "0x20" and data "00"
2022.10.26 15:33:35.012 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD001" with data type "0x1B" and data "00:00:00:00"
2022.10.26 15:33:35.016 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD002" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:35.019 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD003" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:35.022 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD004" with data type "0x23" and data "00:00:00:00"
2022.10.26 15:33:35.026 (wrn) zigbee:    No property found for device "a4:c1:38:50:33:d8:30:07" endpoint "0x01" cluster "0xE001" attribute "0xD005" with data type "0x23" and data "00:00:00:00"

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/9fc586ed0aca63fb6d3d2fb3dcef29994c0652cf

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/9fc586ed0aca63fb6d3d2fb3dcef29994c0652cf
