### ISSUE TITLE
Совместимость единицы измерения мощности с Home Assistant

### ISSUE THREAD

**Issue by Deniom3** [u236/homed-service-zigbee#63]
При добавлении устройства с потреблением энергии Home Assistant не распознает единицу измерения. Для корректного использования надо kWh. Проверял на TUYA TS011F Smart Plug with Power Monitoring.

Ошибка из HA: Entity sensor.bedroom_socket_energy (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'kW·h' which is not a valid unit for the device class ('energy') it is using; expected one of ['MWh', 'MJ', 'kWh', 'GJ', 'Wh'];

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/204523d0f339ac1428c688d338c2929d9cd9f9f9
