### ISSUE TITLE
Перезагрузка хомед-зигби через топик mqtt

### ISSUE THREAD

**Issue by Sborkahome** [u236/homed-service-zigbee#67]
Прошу сделать возможность перезагружать хомед-зигби командой через топик mqtt.

**Comment by u236** [comment]
добавил в https://github.com/u236/homed-service-zigbee/commit/c491abbd11f4d297e22f7647abd9ec785283c585, чтобы перезагрузить службу, нужно отправить сообщение
```json
{
    "action": "restartService"
}
```
в топик
```
homed/command/zigbee
```

**Comment by Blacksli** [comment]
Для исключения проблем с ретайном проще всего чистить топик после получения команды

**Comment by u236** [comment]
> Для исключения проблем с ретайном проще всего чистить топик после получения команды

https://github.com/u236/homed-service-zigbee/commit/197480b7bcae3ffcc00c1745211fd78fe90f060a
