### ISSUE TITLE
Нет indicator_mode

### ISSUE THREAD

**Issue by vasyna** [u236/homed-service-zigbee#69]
TUYA TS011F Smart Plug with Power Monitoring
Manufacturer name _TZ3000_zloso4jk
Manufacturer name _TZ3000_5f43h46b

В exposes отсутствует indicator_mode

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/2de154b8cb0b643e4be772e0f44261c797257c5b
