### ISSUE TITLE
Perenio Smoke Sensor

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#7]
2022.10.26 15:49:13.207 (inf) zigbee:    Device "00:15:8d:00:00:c2:9a:29" joined network with address "0xB90F"
2022.10.26 15:49:13.721 (inf) zigbee:    Device "00:15:8d:00:00:c2:9a:29" node descriptor received, manufacturer code: "0x1037"
2022.10.26 15:49:14.256 (inf) zigbee:    Device "00:15:8d:00:00:c2:9a:29" active endpoints received: "0x01"
2022.10.26 15:49:23.957 (wrn) zigbee:    Device "00:15:8d:00:00:c2:9a:29" interview aborted: "active endpoints request failed"
2022.10.26 15:49:33.957 (wrn) zigbee:    Device "00:15:8d:00:00:c2:9a:29" interview aborted: "endpoint 0x01 simple descriptor request failed"
2022.10.26 15:50:39.876 (inf) zigbee:    Device "00:0d:6f:00:0e:f3:e2:38" joined network with address "0x6162"
2022.10.26 15:50:40.883 (inf) zigbee:    Device "00:0d:6f:00:0e:f3:e2:38" node descriptor received, manufacturer code: "0x120B"
2022.10.26 15:50:41.889 (inf) zigbee:    Device "00:0d:6f:00:0e:f3:e2:38" active endpoints received: "0x01"
2022.10.26 15:50:42.901 (inf) zigbee:    Device "00:0d:6f:00:0e:f3:e2:38" endpoint "0x01" simple descriptor received
2022.10.26 15:50:47.942 (inf) zigbee:    Device "00:0d:6f:00:0e:f3:e2:38" endpoint "0x01" IAS zone enrolled
2022.10.26 15:50:47.951 (wrn) zigbee:    Device "00:0d:6f:00:0e:f3:e2:38" manufacturer name "HEIMAN" unrecognized
2022.10.26 15:50:47.956 (inf) zigbee:    Device "00:0d:6f:00:0e:f3:e2:38" manufacturer name is "HEIMAN" and model name is "SmokeSensor-EM"
2022.10.26 15:50:47.960 (inf) zigbee:    Device "00:0d:6f:00:0e:f3:e2:38" interview finished

**Comment by u236** [comment]
Added in https://github.com/u236/homed-service-zigbee/commit/75f7e5e16f9f0eac333bb6f4ea45aa67a05ff075.
