### ISSUE TITLE
поддержка счетчика импульсов/воды от modkam

### ISSUE THREAD

**Issue by Crazy-Child** [u236/homed-service-zigbee#70]
поддержка счетчика воды от modkam
https://modkam.ru/2021/04/29/schetchik-impulsov-zigbee/

**Comment by Crazy-Child** [comment]
![Безымянный1](https://github.com/u236/homed-service-zigbee/assets/102763254/49188be7-2a10-453e-ae6f-ef72df5c4c1b)
![Безымянный](https://github.com/u236/homed-service-zigbee/assets/102763254/4c661790-2020-41e2-93b3-f3525d31965b)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/d2c130ecbbe980293313360ab52ca0d18380245a
