### ISSUE TITLE
поддержка датчика co2 от modkam

### ISSUE THREAD

**Issue by Crazy-Child** [u236/homed-service-zigbee#71]
поддержка датчика co2 от modkam
https://modkam.ru/2020/09/28/datchik-co2-zigbee/

**Comment by Crazy-Child** [comment]
![Безымянный4](https://github.com/u236/homed-service-zigbee/assets/102763254/39150744-014a-492e-9d96-7dd428abf7db)
![Безымянный3](https://github.com/u236/homed-service-zigbee/assets/102763254/4dd62c8b-d134-43f3-80e9-2a77b459b01e)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/373832e9a667dba61245ebadc696f316233fcb24
