### ISSUE TITLE
перестал работать датчик Aqara FP1 Presence Detector RTCZCGQ11LM в версии 3_5_0

### ISSUE THREAD

**Issue by Sborkahome** [u236/homed-service-zigbee#75]
в версии 3_5_0 перестал работать датчик Aqara FP1 Presence Detector RTCZCGQ11LM, откат на версию 3_4_6 возобновляет работу датчика.
Из всех параметров в версии 3_4_6
{
  "linkQuality": 255
  "detectionMode": "undirected",
  "distanceMode": "middle",
  "event": "leave",
  "linkQuality": 232,
  "occupancy": false,
  "outageCount": 2,
  "sensitivityMode": "high",
  "temperature": 29
}

в версии 3_5_0 приходят только
{
  "linkQuality": 232,
  "outageCount": 2,
  "temperature": 29
}

**Comment by u236** [comment]
исправлено в https://github.com/u236/homed-service-common/commit/7cd739ba55947b9eb6f738fdf1b6d1cf4e9e7fc7
