### ISSUE TITLE
Не корректный logical type конечного устройства (coordinator вместо end device) 

### ISSUE THREAD

**Issue by DGMiron** [u236/homed-service-zigbee#76]
Версия homed 3.5.1
Шлюз  перенио с EZSP,  openwrt
Датчик Perenio PECMS01 опознаётся как координатор. В версии homed 3.4.6 как и положено - end device

![Снимок экрана от 2023-09-12 12-53-05](https://github.com/u236/homed-service-zigbee/assets/88690230/42ccbf0c-081e-419b-8ecc-8a0d0e98915f)

 
[database.txt](https://github.com/u236/homed-service-zigbee/files/12585542/database.txt)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/22c62218f0b35fba295402f90f2ca5db78be2739
