### ISSUE TITLE
не все exposes в датчике движения TS0202

### ISSUE THREAD

**Issue by Crazy-Child** [u236/homed-service-zigbee#77]
не все exposes есть, относительно z2m
процент заряда батареи не показывает, даже после месяца использования
![Безымянный](https://github.com/u236/homed-service-zigbee/assets/102763254/c714e3f8-2fc0-4432-bc85-5b68f6228c76)
![Безымянный1](https://github.com/u236/homed-service-zigbee/assets/102763254/56169b9a-fe5d-4085-8027-0400c7e9df6b)
![Безымянный2](https://github.com/u236/homed-service-zigbee/assets/102763254/9d172508-9db5-411a-b82a-a8db378a0e52)
![Безымянный3](https://github.com/u236/homed-service-zigbee/assets/102763254/936a0a0f-8060-4931-bb15-da319383e969)
![Безымянный4](https://github.com/u236/homed-service-zigbee/assets/102763254/6d0c49b4-a838-49f7-b472-3f2d3e8cb715)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/eeeaf5ec25c0c64c3cf33b288b8b2d2c67c33021
