### ISSUE TITLE
отправка uart команды через mqtt

### ISSUE THREAD

**Issue by Sborkahome** [u236/homed-service-zigbee#79]
Если есть время и желание, прошу сделать для модулей прошитых ptvo возможность отправки uart команда через mqtt.
Типа такого https://ptvo.info/zigbee-configurable-firmware-features/uart/

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/fc25e16ba4b83a449f09c2647167bc366ad9d8af
