### ISSUE TITLE
Please add IKEA Drivers

### ISSUE THREAD

**Issue by yvh65** [u236/homed-service-zigbee#83]
Включите, пожалуйста в список поддерживаемых устройств драйверы Икеа. Они определяются как "TRADFRI driver for wireless control (30 watt) ", "TRADFRI driver for wireless control (10 watt)"

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/a7a53432f32a0b87ec8ee9cb1fe3bf3175196175
