### ISSUE TITLE
Добавьте поддержку устройства Aqara Wireless WXKG12LM

### ISSUE THREAD

**Issue by domostroitel** [u236/homed-service-zigbee#84]
Кнопка Aqara
"singleClick", "doubleClick", "hold"

![2023-10-17 12-08-46](https://github.com/u236/homed-service-zigbee/assets/11273751/92f6e769-cc3c-4e42-84bf-9226876c472b)

**Comment by domostroitel** [comment]
2023.10.17 12:15:50.752 (inf) zigbee:    Device "Aquara WXKG12LM" endpoint "0x01" cluster "0x0012" attribute "0x0055" report received with type "0x21" and data "01:00" and transaction id 50
2023.10.17 12:15:50.876 (wrn) zigbee:    No property found for device "Aquara WXKG12LM" endpoint "0x01" cluster "0x0012" attribute "0x0055" report with type "0x21" and data "01:00"

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/74f64f4611edda3756c7da642120a265fcf103c4
