### ISSUE TITLE
Добавьте поддержку Tuya ZWT198

### ISSUE THREAD

**Issue by bearklake** [u236/homed-service-zigbee#88]
https://www.zigbee2mqtt.io/devices/ZWT198.html
https://github.com/itavero/homebridge-z2m/blob/master/docs/devices/tuya/zwt198.md

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/676b63af9c081d4bf7b98bc26cfed6f8d078e33d
