### ISSUE TITLE
Поддержка пульта IKEA E1810

### ISSUE THREAD

**Issue by Jager-f** [u236/homed-service-zigbee#89]
Пульт определяется и проходит интервью, но не шлет события
![image](https://github.com/u236/homed-service-zigbee/assets/34707843/da1a7332-2b60-431f-828d-e1c879cbd720)
https://www.zigbee2mqtt.io/devices/E1524_E1810.html

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/2eecad47cac15a03071d06f303be2fe1f89a9730
