### ISSUE TITLE
Life Control VOC Sensor MCLH-08

### ISSUE THREAD

**Issue by d51x** [u236/homed-service-zigbee#9]
2022.10.26 16:17:02.011 (inf) zigbee:    Device "00:15:8d:00:00:da:9f:12" joined network with address "0x4337"
2022.10.26 16:17:03.080 (inf) zigbee:    Device "00:15:8d:00:00:da:9f:12" node descriptor received, manufacturer code: "0x1037"
2022.10.26 16:17:06.076 (inf) zigbee:    Device "00:15:8d:00:00:da:9f:12" active endpoints received: "0x01"
2022.10.26 16:17:07.085 (inf) zigbee:    Device "00:15:8d:00:00:da:9f:12" endpoint "0x01" simple descriptor received
2022.10.26 16:17:08.094 (wrn) zigbee:    Device "00:15:8d:00:00:da:9f:12" model name "VOC_Sensor" unrecognized
2022.10.26 16:17:08.098 (inf) zigbee:    Device "00:15:8d:00:00:da:9f:12" manufacturer name is "Nexturn" and model name is "VOC_Sensor"
2022.10.26 16:17:08.102 (inf) zigbee:    Device "00:15:8d:00:00:da:9f:12" interview finished

**Comment by u236** [comment]
Added in https://github.com/u236/homed-service-zigbee/commit/75f7e5e16f9f0eac333bb6f4ea45aa67a05ff075.

**Comment by d51x** [comment]
интервью проходит успешно, но данные не шлет

**Comment by u236** [comment]
исправил в https://github.com/u236/homed-service-zigbee/commit/3908e7bff419ee732402379391e5730f25f1ab54
