### ISSUE TITLE
По возможности добавить поддержку IKEA-VINDRIKTNING_ZIGBEE от Efekta

### ISSUE THREAD

**Issue by Crazy-Child** [u236/homed-service-zigbee#92]
По возможности добавить поддержку IKEA-VINDRIKTNING_ZIGBEE от Efekta
https://github.com/smartboxchannel/IKEA-VINDRIKTNING_ZIGBEE_I_II_III

![image](https://github.com/u236/homed-service-zigbee/assets/102763254/4f1ac12e-5b64-412c-8858-837d4f6296d3)
![image](https://github.com/u236/homed-service-zigbee/assets/102763254/48a9ff94-a6ab-4c9f-b163-e8657135901c)
![image](https://github.com/u236/homed-service-zigbee/assets/102763254/ad3a3d4b-82a6-40ff-bbbd-be441fc6a065)
![image](https://github.com/u236/homed-service-zigbee/assets/102763254/7f9fdf65-5002-4c87-888d-d18324270b21)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/96d525acd2657bc057d6bea25c2a048a746e3067
