### ISSUE TITLE
Добавить поддержку Smart Switch 1 switch (X711A) 	_TYZB01_xfpdrwvc/TS0011

### ISSUE THREAD

**Issue by S1EA** [u236/homed-service-zigbee#95]
![Снимок экрана от 2023-12-02 11-19-55](https://github.com/u236/homed-service-zigbee/assets/45253501/e2aff9a8-37ca-46b4-99e6-025a59937e00)
![Снимок экрана от 2023-12-02 11-21-12](https://github.com/u236/homed-service-zigbee/assets/45253501/a43cb5eb-22b1-404d-82d6-667cca491f8b)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/d67468f77ee23211bfe896f7922e186ea15a7c7e
