### ISSUE TITLE
Добавить поддержку. Датчик CO2 SLS/AirQMon

### ISSUE THREAD

**Issue by S1EA** [u236/homed-service-zigbee#96]
![sls_ 2023-12-02 11-36-51](https://github.com/u236/homed-service-zigbee/assets/45253501/90f5fd3b-8eca-4eca-a9dd-ac455d126c7c)
![sls_2023-12-02 11-35-47](https://github.com/u236/homed-service-zigbee/assets/45253501/c524a0ca-8d27-49c3-acfc-b8ffc7268ebd)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/d67468f77ee23211bfe896f7922e186ea15a7c7e

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/d67468f77ee23211bfe896f7922e186ea15a7c7e
