### ISSUE TITLE
По возможности добавить поддержку датчику температуры\влажности _TZE200_9yapgbuv

### ISSUE THREAD

**Issue by Crazy-Child** [u236/homed-service-zigbee#97]
По возможности добавить поддержку датчику температуры\влажности _TZE200_9yapgbuv

https://www.zigbee2mqtt.io/devices/ZTH02.html

![image](https://github.com/u236/homed-service-zigbee/assets/102763254/3ae18d52-a9ed-463b-85f8-9cd20a3488cf)
![image](https://github.com/u236/homed-service-zigbee/assets/102763254/d310507c-5d87-418f-ba02-dfa23c9f949f)
![image](https://github.com/u236/homed-service-zigbee/assets/102763254/bb489705-5712-4c30-b55a-6bab0283ab89)
![image](https://github.com/u236/homed-service-zigbee/assets/102763254/82442e84-c625-4706-b386-832659ed58ea)

**Comment by u236** [comment]
https://github.com/u236/homed-service-zigbee/commit/b38179a262a29e96bb542cff223c55fdd7b582a2
